🚀 0단계 - 기본 코드 준비
next-step/jpa-entity-manager pull request #100
Opened 2024-02-25 14:58 UTC by djawnstj

안녕하새요, 종민님
1주차에 작업한 코드와 피드백을 추가 반영하여 2주차 첫 PR 올립니다!

이번 미션 잘 부탁드립니다!

2024-02-25 15:23 UTC, jongmin4943 requested changes
안녕하세요 준서님!
`Entity 구현` 미션을 함께하게 된 리뷰어 윤종민입니다 😁

기본 코드 준비된 것을 확인해보니 `이전 미션 코드 가져오기` 가 이상하게 된 것 같아요 😢 
Test 클래스들이 main 하위의 util 패키지 밑에 있어서 실행해볼 수가 없더라구요 😭

다시 한번 확인 해주신 후 재요청 주시면 감사하겠습니다 🙏

2024-02-25 22:40 UTC, djawnstj commented
ㅠㅠ 코드 복사할때 잘못 옮겨졌네요.
죄송합니다.

2024-02-26 03:47 UTC, jongmin4943 commented on src/test/java/persistence/sql/dml/DefaultDmlQueryBuilderIntegrationTest.java
> +public class DefaultDmlQueryBuilderIntegrationTest {
여기도 없는것 같네요 😭

2024-02-26 06:45 UTC, djawnstj commented
으아 미션 시작부터 정말 죄송합니다ㅠㅠ
아침에 비몽사몽하게 PR 올리려다가 실행도 안해보고 그냥 무지성으로 올려버렸네요ㅜㅜ
테스트 코드 검증까지 확인해서 다시 올려드립니다.

번거롭게 해드려서 정말 죄송합니다!

2024-02-26 08:52 UTC, jongmin4943 approved these changes
안녕하세요 준서님!
저도 처음에 Next step 에서 코드 옮기기 할 때 헤맸답니다 😅 이번에 해보셨으니 다음에는 좀 더 수월 하실거에요 👍 

이전 주차의 미션을 굉장히 깔끔하게 잘 해주셨네요 💯 
빠른 진행을 위해 0단계는 바로 머지하도록 하겠습니다!
이번 미션 잘 부탁드려요~ 🙏

2024-02-26 08:52 UTC, jongmin4943 commented on src/test/java/persistence/entity/SimpleEntityManagerTest.java
> +    }
`@AfterEach` 로 매 테스트 종료시 비워주고 있는데 단순히 `remove` 를 호출하고 나서 `select` 한 값이 비었는지 확인하면 정확히 검증이 될까요? 🤔

2024-02-26 08:52 UTC, jongmin4943 commented on src/test/java/persistence/sql/TestJdbcServerExtension.java
> +        jdbcTemplate = new JdbcTemplate(server.getConnection());
오우 Extension 으로 DB 통합테스트 환경 구축 💯

2024-02-26 08:52 UTC, jongmin4943 commented on src/test/java/persistence/sql/dml/InsertQueryStringValueBinderTest.java
> +}
클래스의 마지막 줄은 개행문자를 넣어주세요!
차이점이 궁금하시면 아래 링크를 참고해주세요
https://velog.io/@doondoony/posix-eol

intelliJ 에서
Preferences -> Editor -> General -> Ensure line feed at file end on save 를 체크하시면
파일 저장 시 마지막에 개행문자를 자동으로 넣어줍니다!

2024-02-26 08:53 UTC, merged