[Step4 - EntityEntry] 김현태 미션 제출합니다.
next-step/jpa-entity-manager pull request #119
Opened 2024-02-29 13:13 UTC by Hyunta

안녕하세요 정원님,
4단계 EntityEntry 엔터티 상태 추가하기 미션을 진행해봤습니다.
남겨주신 커멘트를 도움받아 `EntityMeta` 클래스를 추가하니 구조가 훨씬 파악하기 쉽게 바뀐 것 같습니다.
미션을 진행하면서 점점 하이버네이트에 대한 이해도가 올라가고 있음을 느낍니다👍🏻
말씀해주신 것처럼 Transaction과 항상 같이 써오다가 없이쓰니 의문이 들었던 것 같습니다.
좋은 피드백 감사합니다ㅎㅎ

추가로 남겨주신 `flush()` 를 어떻게 구현해야할지도 계속 고민해보겠습니다.
먼저 PR을 올려놓고 피드백을 받으면서, 생각이 나는데로 해당 PR 건에 flush 내용에 대해서 추가하도록 하겠습니다.

2024-03-01 10:24 UTC, jwee0330 commented
> 여전히 조금 해결이 안된 고민이 있는데요, save()할 때 persist, merge 분기처리를 하기 위한 `isNew()` 메서드 구현에서 헷갈립니다. 엔티티가 새로운 엔티티인지, DB에 존재하는 엔티티인지 확인하는 메서드를 구현하기가 어렵습니다.
> 
> 뭔가 EntityEntry를 만들면 처리할 수 있을까 했는데, PersistenceContext 안에서 관리를 하다보니 접근하기가 어렵습니다. 입력된 Entity의 ID 값의 유무에 따라 구분하기에는 사용자가 입력한 ID 값이 있으면 또 판단할 수가 없겠더라구요. 그러면 1) 1차 캐시에 존재하는지 확인 2) DB의 generatedKey 를 통해 확인 이런 절차를 거쳐야할 것 같은데 2)의 경우 select 쿼리까지 발생하게되니 이렇게 사용하지는 않을 것 같고, 1번처럼 캐시에 접근할 수 있는 수단이 존재해야 하는건가요?

안녕하세요 현태님🙂
CustomRepository 에서 save 할때 체크하는 isNew 는 **해당 엔티티가 영속성컨텍스트에서 관리되고 있는가?** 입니다.
DB에 실제 존재하는가에 대한 관심까지는 없답니다! 1번 1차캐시에 존재하는지만 확인하시면 됩니다 😀

2024-03-01 10:45 UTC, jwee0330 requested changes
안녕하세요 현태님 🙂
미션 구현 속도가 상당하십니다 👍  얼마나 치열하게 고민하고 계신지 느껴지네요.
몇가지 피드백 드린 부분있어요. 확인하고 다시 PR 요청 부탁드립니다.
궁금한점은 편하게 DM 보내주세요 :)

2024-03-01 10:45 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityMeta.java
> +    private final EntityEntry entityEntry;
제가 생각했던 엔터티메타와 약간 다르긴합니다.
Object entity 와 EntityEntry 는 EntityMeta 에 존재하는게 약간 어색하게 느껴지는데요
엔터티 메타는 정말 메타정보만 갖고있는게 좋을것 같다고 생각해요 🙂

2024-03-01 10:45 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityMeta.java
> +    }
```suggestion
    public boolean isNew(Object entity) {
        return ValueExtractor.extract(entity, id) == null;
    }
```
entity 는 엔터티 메타정보가 아니다 보니 메시지로 전달하여 처리하도록 변경하는게 더 객체의 책임에 맞다고 느껴지는데
현태님은 혹시 어떻게 생각하시나요?

2024-03-01 10:45 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityPersister.java
> +    void delete(EntityMeta entity);
이부분도 엔터티 퍼시스터에서 insert, update, delete 작업을 할 때 Object 만 메시지로 전달받고
이미 엔터티 퍼시스터는 EntityMeta 정보를 갖고 있고 이를 활용하도록 하는 방법은 어떻게 생각하세요?
엔터티메타를 메시지로 전달하게 되면 엔터티 퍼시스터를 사용하는 쪽에서는 어쩔수없이 엔터티메타라는 필요없는 의존성이 생길것 같습니다🥲

2024-03-01 10:45 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityStatus.java
> +}
👍

2024-03-01 12:20 UTC, Hyunta commented on src/main/java/persistence/entity/EntityPersister.java
> +    void delete(EntityMeta entity);
제가 EntityMeta를 잘못 이해했었나봐요ㅎㅎ
말하신데로 수정했습니다

2024-03-01 12:21 UTC, Hyunta commented on src/main/java/persistence/entity/EntityMeta.java
> +    private final EntityEntry entityEntry;
의도하신바를 잘 파악하지 못했었네요ㅋㅋㅋ
수정하였습니다!

2024-03-01 12:21 UTC, Hyunta commented on src/main/java/persistence/entity/EntityMeta.java
> +    }
EntityMeta에 맞도록 수정하도록 하겠습니다!

2024-03-01 13:01 UTC, Hyunta commented
안녕하세요 정원님,
EntityMeta의 용도에 맞게 수정하였습니다.

추가로 flush에 대해서 고민해봤습니다.
DirtyChecking에 대해서는 구조를 크게 바꾸지 않고 반영할 수 있을 것 같아서 추가해봤습니다.
merge할 때 바로 쿼리를 날리는 것이 아니라 1차 캐시에만 변경이 되도록 수정하였습니다.
이후 flush를 진행하면 PersistenceContext에서 snapShot에 있는 키들을 기반으로 1차 캐시의 값들과 차이가 있다면 타겟으로 지정해서 반환해줍니다. EntityManager는 이를 받아서 update 쿼리를 날려주고 entityEntry를 수정해도록 구현했습니다.

나중에 persist, remove에 대해서도 고민은 해봤는데 entityManager의 flush 할 때
삭제된 엔티티에 대해서는 entityEntry의 값을 보고 처리하면 될 것 같은데,
새로운 엔티티에 대해서는 찾아보니 persistedState? 에 보관한 뒤에 처리하는 것 같은데 맞을까요? 이 부분이 좀 궁금합니다!

2024-03-02 06:39 UTC, jwee0330 commented
> 안녕하세요 정원님, EntityMeta의 용도에 맞게 수정하였습니다.
> 
> 추가로 flush에 대해서 고민해봤습니다. DirtyChecking에 대해서는 구조를 크게 바꾸지 않고 반영할 수 있을 것 같아서 추가해봤습니다. merge할 때 바로 쿼리를 날리는 것이 아니라 1차 캐시에만 변경이 되도록 수정하였습니다. 이후 flush를 진행하면 PersistenceContext에서 snapShot에 있는 키들을 기반으로 1차 캐시의 값들과 차이가 있다면 타겟으로 지정해서 반환해줍니다. EntityManager는 이를 받아서 update 쿼리를 날려주고 entityEntry를 수정해도록 구현했습니다.
> 
> 나중에 persist, remove에 대해서도 고민은 해봤는데 entityManager의 flush 할 때 삭제된 엔티티에 대해서는 entityEntry의 값을 보고 처리하면 될 것 같은데, 새로운 엔티티에 대해서는 찾아보니 persistedState? 에 보관한 뒤에 처리하는 것 같은데 맞을까요? 이 부분이 좀 궁금합니다!

안녕하세요 현태님 코멘트로 어느정도 답변을 드리긴 했는데요 조금 추가하자면
EntityManager 가 Entity 의 상태 변경 요청을 받을때마다 EntityEntry 의 Status 를 업데이트 하게 되죠.
그리고 flush 가 호출될 때 flush 해야하는 EntityEntry 의 Status 인지 flushable 이라는 api 로 플러시 대상인 엔티티를 체크하는 로직이 존재합니다.
```
private static boolean flushable(EntityEntry entry) {
    final Status status = entry.getStatus();
        return status == Status.MANAGED
        || status == Status.SAVING
        || status == Status.READ_ONLY;
}
```
MANAGED, SAVING, READ_ONLY 상태만 flush 의 대상이 되고, 질문주신 insert 는 SAVING 상태일때 실제 insert 쿼리가 발생합니다 :)
잘 이해가 안되시거나 추가 궁금점은 DM 또는 편하게 이야기 해주세요 :)

2024-03-02 06:39 UTC, jwee0330 approved these changes
안녕하세요 현태님🙂
과제에는 없는 요구사항 이었는데도 반영해 주셔서 감사합니다 👍 
요구사항도 만족하고 깔끔하게 잘 구현해주셨습니다. 정말 고생하셨어요.
질문 주신 부분에 대한 답변 남겼으니 다음 단계 진행 하시면서 고민해 보시면 좋을것 같아요.
이후 진행하시는 미션도 제가 지켜보도록 하겠습니다😎

2024-03-02 06:39 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityStatus.java
> +}
위에서 설명드린 것처럼 EntityStatus 와 EntityEntry 의 Status 가 존재하는데요
위 상태값들은 EntityEntry 의 Status 로 보여집니다 🙂
EntityEntry 는 PersistenceContext 에서 각 엔티티별로 관리하도록 해보시는건 어떨까요?
EntityEntry 의 Status 를 가지고 PersistenceContext 에서 엔티티 영속화 상태(EntityState) 를 만들어 내는 개념입니다.

2024-03-02 06:39 UTC, merged