🚀 4단계 - EntityEntry
next-step/jpa-entity-manager pull request #170
Opened 2024-03-12 14:52 UTC by qwe5507

step4 리뷰요청 드립니다.

DM으로 너무 괴롭혀서 죄송합니다. ㅜ

잘 구현 했는지 모르겠네요 잘부탁드립니다! 

많이 도와주셔서 감사해요!

2024-03-13 12:03 UTC, leeyohan93 requested changes
안녕하세요 진현님 😄 
EntityEntry에 대해 고민해보시면서 많은 포인트를 짚어주시고 계신 것 같아요!
덕분에 저도 함께 배워가는 것 같습니다 👍 👍 
질문 주신 부분들에 대한 코멘트를 남겨두었으니 확인 부탁드릴게요!
마지막까지 화이팅입니다 🔥

2024-03-13 12:03 UTC, leeyohan93 commented on src/main/java/persistence/sql/entity/impl/EntityManagerImpl.java
> +            throw new IllegalAccessException();
체크 예외를 활용해주셨네요! 👍 
진현님은 어떠한 기준으로 체크 예외와 언체크 예외를 구분하여 사용하시는 지 궁금합니다 😄

2024-03-13 12:39 UTC, qwe5507 commented on src/main/java/persistence/sql/entity/impl/EntityManagerImpl.java
> +    public Object merge(final Object entity) throws IllegalAccessException {
감사합니다! 
덕분에 모르던 내용을 많이 알게됩니다.

2024-03-16 09:40 UTC, qwe5507 commented on src/main/java/persistence/sql/entity/impl/EntityManagerImpl.java
> +        if (existEntityEntry != null && existEntityEntry.isReadOnly()) {
>   - 이미 존재하는 엔티티를 영속화하려는 경우 EntityExistsException 발생
- 이미 존재하는 엔티티를 어떻게 구분할까요? DB일가요? 아니면 영속성 컨텍스트 인가요?ㅜ

> 그렇다면 EtntityEntry를 확인하는 것보다는 객체의 id 값을 확인하고 예외를 던지는 것은 어떨까요?
- spring data jpa를 사용한다고 하면 id가 없는것을 확인하고, persist()에 들어오는데, spring data jpa를 사용하지 않는다고 가정하고 entityManager를 그대로 사용 했을 때 id가 있는경우 예외를 발생시키라는 말씀이 맞을까요?

2024-03-16 10:17 UTC, qwe5507 commented on src/main/java/persistence/sql/entity/impl/EntityManagerImpl.java
> +        if (existEntityEntry != null && existEntityEntry.isReadOnly()) {
실제 persist()와 merge()의 헷갈리는 부분이 많아서 flow를 정리 해보았습니다.
1번, 2번은 flow 검토를 부탁드리고 3번은 예외 처리에 대한 질문 입니다.

항상 답변 잘해주시는데, 제가 잘 못따라 가는것 같아서 죄송합니다ㅜ_ㅜ 

---

**1. Persist() flow**
Spring data jpa를 사용하지않고 엔티티매니저를 그대로 사용 할 때는 id가 있는경우 예외가 발생 
- Spring data jpa를 사용한다면, isNew()를 통해 id가 없는 경우에만 실행되기 때문에 예외 발생할 확률 X

무조건 처음 insert되는 엔티티이기 때문에 영속컨텍스트에 조회할 필요없이 영속성 컨텍스트에 저장 후 db 에 저장
- 강의에서는 flush가 없기때문에 바로 저장

---

**2. merge() flow**
Spring data jpa를 사용하는 경우에는 isNew()메소드를 통해  id가 무조건 있기 떄문에 영속성 컨텍스트에서 엔티티 조회 시도 
- 영속성 컨텍스트에 있다면 엔티티 세팅 
- 영속성 컨텍스트에 없다면 db에서 조회 
    - db에 없다면 insert 후 영속성 컨텍스트에 세팅
    - db에 있다면 조회하여 영속성 컨텍스트에 세팅

그후 flush할때 isDirty()가 실행 되는되서 update 발생 
- 강의에서는 flush가 없기떄문에 isDirty()로직 반영 후 update 또는 insert로 통합 하는 로직을 구현해야함

---

**3. merge() 예외 케이스**
DM으로 merge()시 엔티티가 존재하지 않아 IllegalArgumentException가 발생하는  경우를 아래와 같이 답변주셨는데요.
```
JPA에서는 merge() 호출 시 존재하지 않는 엔티티가 넘어온다면 IllegalArgumentException을 발생한다고 명시하고 있습니다!
…
조금 더 자세히 이야기드리면 데이터베이스에서는 지워졌지만 영속성 컨텍스트에 관리되어 남아있는 엔티티가 들어왔을 때 입니다!
```
flow를 정리하고보니 데이터베이스에서는 없지만, 영속성 컨텍스트에 관리되어 남아있는경우가 언제일까요? 

예외가 발생할 수 있는 케이스
- Dirty checking을 이용하기 위해 load후(영속성 컨텍스트에 저장), 데이터 변경, save()메소드를 통해 flush를 하려고 하는데 데이터베이스에 값이 없기 떄문에 예외발생 
제가 생각한 위 케이스가 맞나요?

2024-03-17 08:04 UTC, qwe5507 commented on src/main/java/persistence/sql/entity/impl/EntityManagerImpl.java
> +        if (existEntityEntry != null && existEntityEntry.isReadOnly()) {
pk가 자동 생성인 경우 인데, id가 있는경우 예외 발생, 
pk가 자동 생성이 아니고, persistenceContext에 이미 존재하면 EntityExistsException가 발생하게 변경하였습니다!

2024-03-17 08:27 UTC, qwe5507 commented
리뷰 재요청 드립니다! 
merge와 persist()예외처리 부분을 변경하였습니다. 

테스트 해보니, merge()실행 시에 IllegalArgumentException이 발생하는 경우가 삭제된 엔티티의 경우 발생하는 것 같아서 GONE상태일 때 예외가 발생하게 변경하였습니다.
그리고  readonly상태여도 insert는 발생하는것 같고, 변경감지만 발생하지 않는것 같아서, isDIrty()를 처리할 때 read_only면 발생하지 않게 끔 변경하였습니다!

2024-03-17 11:54 UTC, leeyohan93 approved these changes
안녕하세요 진현님! 😄 
피드백 반영에 더불어 더 자세한 로직 흐름을 분석해서 개선해주셨네요 💯 💯 
이번 단계는 여기서 머지하도록 할게요.
더 많이 고민하고 경험해보시는 것만큼 얻어가시는 것이 많으셨을 것이라 생각합니다! 😄 
고생 많으셨고 다음 미션들도 화이팅입니다 🔥

2024-03-17 11:54 UTC, merged