[🚀 3단계 - First Level Cache, Dirty Check] 윤주리 미션 제출합니다.
next-step/jpa-entity-manager pull request #180
Opened 2024-03-16 17:35 UTC by jurlring

정원님 안녕하세요!

3단계 제출합니다~! 이번에도 잘 부탁드려요 :) 

아래와 같이 요구사항 구현해보았어요

1. 요구사항1 - PersistenceContext 구현체를 만들어 보고 1차 캐싱을 적용해보자
- PersistenceContext에 entitiesByKey Map 구현하여 1차 캐시로 사용하고 EntityManager에서 
  - persist 시 1차 캐시에 추가하도록 구현
  - remove 시 1차 캐시에서 제거하도록 구현
  - find, merge 시 entitiesByKey에 존재하는지 확인 후 있으면 반환 없으면 Loader에서 조회하도록 구현

2. 요구사항2 - snapshot 만들기
- PersistenceContext에 entitySnapshotsByKey 구현
- find 시, 조회된 entity entitySnapshotsByKey에 저장하여 초기 상태 저장될 수 있도록 구현

3. 요구사항3 - 더티체킹 구현
- 요구사항 2에서 구현한 엔티티를 조회할 때 스냅샷을 저장
- EntityManager.persist에선 비영속 상태의 엔티티가 들어온다고 가정했을 때, 
  - repository에서 save시 id가 없을 경우 persist, id가 있을 경우 merge를 호출하여
  - merge시 엔티티의 상태를 변경되었는지 스냅샷과 비교하여 변경 내용을 감지하도록 구현

2024-03-17 13:27 UTC, jwee0330 requested changes
안녕하세요 주리님 🙂

몇가지 수정이 필요한 부분에 대해서 피드백 드렸는데 
확인하신 뒤 수정 후 다시 PR 요청 부탁드릴게요 🙏🏻

업무와 함께 미션을 진행하시는것이 얼마나 힘든 일 인지 잘 알고 있습니다.
강의 기간이 얼마 남지 않았는데요, 끝까지 파이팅 하셨으면 좋겠습니다 💪

2024-03-17 13:27 UTC, jwee0330 commented on src/main/java/domain/Person.java
> +    }
동등성 비교 로직의 추가는 좋은데, merge 에서 euqals 로만 체크하게 되면 과연 이전 객체의 값이 변경되지 않고 보장이 될까요? 🤔

2024-03-17 13:27 UTC, jwee0330 commented on src/main/java/persistence/DefaultEntityManager.java
> +        }
동일 entity 에서 아래 처럼 이름을 변경하는 작업을 했을 때
```
Person 주리 = new Person("주리");
주리.setName("juri");
```
snapshot 과 entity 의 equals 가 실패하게 되는 케이스가 발생할까요?
추가로 스냅샷 정보와 같지 않다면 dirty-check 의해서 update 가 되어야 할 것 같은데
어떻게 생각하시나요? 🤔

2024-03-17 13:27 UTC, jwee0330 commented on src/main/java/persistence/IdMetadata.java
> +    }
Id 값을 래핑 했다기 보다는 entity 에서 id 필드를 찾아오는 역할만 위임한 것으로 보이는데요
상태값과 클래스명이 어울리지 않아 약간 어색한 느낌이 드네요 🥲

2024-03-17 13:27 UTC, jwee0330 commented on src/test/java/persistence/CustomJpaRepositoryTest.java
> +    }
테스트가 온전한 검증을 하지 못하는것 같아요 🥲
아래 코드가 동작하도록 수정 부탁드려요 🙏🏻
clear 메소드는 영속성 컨텍스트의 모든 캐시를 초기화 하는 작업을 해주시면 됩니다!
```suggestion
    @Test
    @DisplayName("person save 시 dirty checking 로직 구현")
    void saveWithDirty() {
        // given
        String name = "name";
        int age = 26;
        String email = "email";
        int index = 1;

        Person person = (Person) repository.save(new Person(name, age, email, index));

        String newName = "newName";
        person.changeName(newName);

        // when
        Person result = repository.save(person);
        repository.clear();
        Person expected = repository.findById(index);

        // then
        assertThat(result.equals(expected)).isTrue();
    }
```

2024-03-17 13:27 UTC, jwee0330 commented on src/test/java/persistence/PersistenceContextTest.java
> +}
마지막줄 개행 추가 부탁드려요!

2024-03-19 12:52 UTC, jurlring commented on src/main/java/persistence/DefaultPersistenceContext.java
> +    }
엔티티가 영속성 컨텍스트에 저장되기 전까지 메모리 할당을 미루려고 지연초기화 될 수 있도록 했던 건데용!
불필요하다고 생각하시나요?

2024-03-19 13:00 UTC, jurlring commented on src/main/java/persistence/DefaultPersistenceContext.java
> +    }
getDatabaseSnapshot는 진짜 DB 조회하여 dirty checking
getCachedDatabaseSnapshot는 1차 캐시 조회하여 dirty checking

이렇게 이해하면 될까요?

2024-03-19 13:01 UTC, jurlring commented on src/main/java/persistence/DefaultEntityManager.java
> +        return (T) find(entity.getClass(), id);
오~~~~~~~~~~~~~~~~ 너무 좋은 생각입니다 👍

2024-03-20 07:39 UTC, jwee0330 commented on src/main/java/persistence/DefaultPersistenceContext.java
> +    }
아 그런 의도라면 addEntity 에만 entity null 체크 추가하면 될 것 같네요!

2024-03-20 07:49 UTC, jwee0330 commented on src/main/java/persistence/DefaultPersistenceContext.java
> +    }
오 넵!! 제 의도를 정확하게 이해하셨어요 :)
실제로 하이버네이트 PersistenceContext 인터페이스의 설명을 보면 명확해져요~
![image](https://github.com/next-step/jpa-entity-manager/assets/54702844/5dcab75d-c903-4ff3-a9da-b04a831b165d)

hibernate 에서는 flush 로직이 동작할때 update 전에 select 가 필요한지 체크하여 select 가 필요할때는 실제 디비조회 후 dirtycheck 를 하고 select 가 필요없다면 캐시된 스냅샷을 사용해요~
<img width="751" alt="image" src="https://github.com/next-step/jpa-entity-manager/assets/54702844/3817f71c-b160-4735-b0fb-687dd2dd0101">

2024-03-22 15:37 UTC, jurlring commented on src/main/java/persistence/DefaultPersistenceContext.java
> +    }
캬 자세한 설명 감사합니다~!!!!!! 정원님 계신 곳으로 절한번 올리겠습니당

2024-03-22 15:40 UTC, jurlring commented on src/main/java/persistence/DefaultPersistenceContext.java
> +    }
혹시 요거 어디서 동작하는건지 알 수 있을까용?

2024-03-22 15:59 UTC, jurlring commented on src/main/java/persistence/DefaultEntityManager.java
> +        }
update가 되는게 맞을 것 같습니다~!

2024-03-22 16:17 UTC, jurlring commented on src/main/java/persistence/DefaultEntityManager.java
> +        }
스냅샷에 entity가 동일한 엔티티라 수정하면 같이 바뀌어서 실패 케이스가 없겠네요..!
스냅샷을 만들 때 값을 복사한 객체를 넣어야할 것 같아요~!

2024-03-22 16:54 UTC, jurlring commented on src/main/java/domain/Person.java
> +    }
아래와 같은 리뷰신가용?
`이전 객체의 값이 변경되지 않고` 이 부분이 이해가 안가는데 더 자세히 설명 주실 수 있나요? 
아래 리뷰는 일단 반영했는데 같은 의미시면 답변 안주셔도 됩니다 ㅎ.ㅎ!

2024-03-22 17:14 UTC, jurlring commented on src/main/java/persistence/IdMetadata.java
> +    }
클래스명이랑 메서드명 수정했습니다

2024-03-22 17:36 UTC, jurlring commented
정원님 리뷰 감사합니다~~ 
merge 구현하면서 궁금한 점이 있는데요!

준영속 상태인지는 영속성 컨텍스트에 존재하는지? 로 판단해야할 것 같다고 생각했는데요!
EntityManager에서 영속성 컨텍스트를 관리하는데 이 엔티티가 어떤 상태인지 어떻게 알고 persist인지 merge인지 판단하는지 궁금해서 구현체를 뒤져보니 id가 null인지로 판단하더라고용??
![스크린샷 2024-03-23 오전 2 31 23](https://github.com/next-step/jpa-entity-manager/assets/78091011/9f1d2c42-90d8-4b29-bf3d-f34b58a2f3f7)
영속성 컨텍스트에 넣은 엔티티의 id를 강제로 null로 만들수도 있을 것 같은데, 왜 이렇게 구현했을까요??ㅎㅎㅎㅎ.. 그냥 궁금해서 여쭤봐용~

2024-03-23 05:04 UTC, jwee0330 commented on src/main/java/domain/Person.java
> +    }
https://github.com/next-step/jpa-entity-manager/pull/180#discussion_r1535843440

아 이렇게 해소되지 않을때의 발생하는 문제점을 이야기 드린부분이에요! 딥카피가 되지 않는다면 이전 객체의 상태로 변경되어 변경점이 항상 없는 부분을 말씀드린 거에요🙂

2024-03-23 05:09 UTC, jwee0330 commented
맞아요ㅎ 강제로 id 를 null 로 변경한다면 동일한 값을 가진 새로운 row 가 데이터베이스에 추가되겠지요! 저는 하이버네이트의 컨셉으로 이해하고 있습니다. 하이버네이트의 영속성 컨텍스트 관리에서도 entitiesByKey 와 같이 키를 기반으로 동작하기 때문에 엔티티매니저에 요청할때 엔티티의 상태에 키가 존재하는지 존재하지 않는지가 중요한 관심사라고 생각해요. 그래서 자연스럽게 이렇게 구현이 되었다고 추측해요🙂

2024-03-23 05:10 UTC, jurlring commented on src/main/java/domain/Person.java
> +    }
아 그래서 스냅샷 저장할 때 값복사해서 저장했습니다 :)

2024-03-23 05:50 UTC, jwee0330 approved these changes
안녕하세요 주리님🙂
피드백 반영 잘 해주셨네요 👍 정말 고생하셨습니다.
다음 단계 진행해주세요 :)
진행 중 궁금한 부분은 DM 부탁드려요
끝까지 파이팅하세요 💪

2024-03-23 05:50 UTC, jwee0330 commented on src/main/java/persistence/DefaultEntityManager.java
>      }
피드백 반영 잘 해주셨어요 :)
다만 해당 책임은 EntityPersister 에 위임해 볼까요?

아래 코드는 hibernate EntityPersister 코드에서 발췌했어요
<img width="712" alt="image" src="https://github.com/next-step/jpa-entity-manager/assets/54702844/c730644d-86ab-49c7-8a90-1a87cd3c49ea">

2024-03-23 05:50 UTC, jwee0330 commented on src/main/java/persistence/DefaultPersistenceContext.java
> +        return snapshotEntity;
리플렉션으로 아예 새로운 클래스로 만들어 주셨군요 :)
deep copy 는 serialize/deserialize 를 통한 더 간단한 방법도 있답니다.

2024-03-23 05:50 UTC, merged