Step3
next-step/jpa-entity-manager pull request #202
Opened 2024-10-22 05:14 UTC by chanho0912

안녕하세요 기륭님! 

이번 과제가 너무 어려워서 혼자 끙끙 앓다가 우선 방향성 맞는 지도 점검 받을 겸 리뷰 요청 드립니다.

제가 고민했던 부분(...?) 구현하려 했던 기능은 

1. persist()시에 id 생성전략에 따라 검증
- auto -> 저장 시 id값이 필요
- identity -> 저장 시 id값이 null or 0이어야 함.

2. 이미 영속된 entity가 persist()에 추가로 전달되면
- 그냥 반환.

3. update()시에 영속성 컨텍스트에서 관리하는 entity가 아니라면 persist() 호출
4. update()시에 영속성 컨텍스트에서 관리하는 entity가 있다면, 전달받은 entity를 영속성 컨텍스트에 추가(머지..?) 하고 스냅샷과 비교하여 변경점 찾은 뒤 수정 쿼리 실행

이정도 인것같은데요, 과정에서 로직이 자꾸 꼬이는 것 같아서 우선 리뷰 요청 보내게 되었습니다. 
잘 부탁드립니다!

2024-10-22 12:17 UTC, NamKey requested changes
안녕하세요 찬호님 😄
고민의 흔적들이 곳곳에 보여서 재밌게 읽었습니다! 👍👍
미션에 대한 전반적인 큰틀은 맞게 이해하시고 구현해주셨습니다! 💯
주로 제가 궁금한 부분들에 대해서 코멘트를 남겼는데 답변주시면 감사하겠습니다!

2024-10-22 12:17 UTC, NamKey commented on README.md
> +      - [x] Auto 전략일때
1/ GenerationStrategy.AUTO 는 어떤 방식으로 ID가 채번될까요?
2/ GenerationStrategy.IDENTITY는 어떤 방식으로 ID가 채번될까요?

2024-10-22 12:17 UTC, NamKey commented on src/main/java/jdbc/JdbcTemplate.java
> +        try (final Statement statement = connection.createStatement()) {
- try-with-resource를 사용하는 부분은 좋았지만 try 안의 try 를 사용하게 되어 가독성이 떨어지네요!

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityKey.java
> +    private final Long id;
EntityKey의 id 타입이 다시 Long으로 변경된 이유가 있을까요?

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityKey.java
> +        tableDefinition.tableId().bindValue(entity, this.id);
TableId의 `bindValue()` 메서드에 대해 [디미터의 법칙](https://mangkyu.tistory.com/147)을 적용해주세요!
해당 동작때문에 EntityKey 클래스가 TableId 클래스에 대해 알게되었네요!

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        final EntityKey entityKey = new EntityKey((Long) id, clazz);
만약 id가 Long 타입이 아니라면 어떻게 될까요?
강제형변환을 해야 되는 코드가 왜 생기게 됐을지 생각해보셨으면 좋겠습니다!

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityPersister.java
> +        return tableDefinition.tableId().hasValue(entity);
tableDefinition.tableId() 를 계속 호출해야 하네요!
꼭 tableDefinition 객체의 tableId에게 value가 있는지 값은 무엇인지 알아봐야할까요?(디미터의 법칙 참고해주세요)

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityPersister.java
> +        entityKey.bindId(entity);
- EntityKey가 생성된 이후에 Id를 바인딩해야 하는 이유가 궁금합니다!
- EntityPersister는 EntityKey를 만들어 Entity와 Id를 바인딩할 책임을 갖고 있는 것이 적절하다고 생각하신 이유가 궁금합니다

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
>          final EntityPersister entityPersister = new EntityPersister(entity.getClass(), jdbcTemplate);
EntityPersister가 persist / update / delete 마다 생성되는데 의도하신 부분일까요?
매호출마다 생성해야 되는 비용을 고려하신 것인지 궁금합니다!

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.isManagedEntity(entity, entityPersister.getEntityId(entity))) {
1/ 업데이트하려고 할 때 캐시에 없다면 저장하는 것이 찬호님의 의도실까요?
2/ 캐시에 없는데, 만약 데이터베이스에 있다면 어떻게 될까요? 😄

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntitySnapshot.java
> +                    final Object currentValue = column.hasValue(entity) ? column.getValueAsString(entity) : null;
current 라는 접두사를 붙인 의미가 어떤 것일까요? 😄

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/PersistenceContextImpl.java
> +    public boolean isManagedEntity(Object entity, Object id) {
Managed 라는 접두사를 붙이신 이유가 궁금합니다!

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/PersistenceContextImpl.java
> +        if (id == null) {
현재 구조에서는 저장되지 않아도 entity의 id가 입력되어야 하기 때문에 해당 부분은 false 가 나오는 케이스는 없는 것으로 이해되는데 맞을까요? 😁
- id가 입력되어 있으면 해당값
- id가 입력되지 않았다면 0(DEFAULT_ID_VALUE)
- 따라서 id가 null 이 나올 수 없어보였습니다!

2024-10-22 12:17 UTC, NamKey commented on README.md
> +      - [x] Auto 전략일때
AUTO는 미션 내용이 아니기 때문에 기존 미션만 생각해주셔도 좋습니다😄

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/sql/definition/ColumnDefinition.java
> +    public void bindValue(Object entity, Object value) {
1/ 해당 부분은 채번되는 ID에 대한 값을 주입할 때만 사용하기 위함일까요?
2/ 만약 그런 의도시라면 걱정되는 부분은 ColumnDefitnion은 Column에 대한 메타정보를 갖고 있는 클래스로 보이는데 해당 클래스가 엔티티에 대해 값을 set 해주는 역할로 느껴져서 적절한 책임인가라는 의문이 들어 질문드립니다! 😄

2024-10-22 12:17 UTC, NamKey commented on src/test/java/persistence/sql/dml/query/UpdateQueryBuilderTest.java
> +        assertAll(
이런 방식으로 검증문을 바꾸신 이유가 궁금합니다! 😄

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        List<String> dirtyColumns = entitySnapshot.getDirtyColumns(persistenceContext.getEntity(entityKey));
JPA의 Dynamic Update에 대해서 아시나요?

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
>      public void update(Object entity) {
자주 사용하는 Hibernate의 EntityManager에는 어떤 메서드가 있는지 아실까요?

2024-10-22 12:17 UTC, NamKey commented on src/main/java/persistence/entity/EntityPersister.java
> +    private Object getId(TableDefinition tableDefinition, Object entity) {
어디선가 중복되지만 미묘하게 다른 로직들이 반복된다는 느낌이 들지 않으시나요? 😄

2024-10-22 12:27 UTC, chanho0912 commented on README.md
> +      - [x] Auto 전략일때
이 부분은 제가 조금 착각을 한 것 같네요 ㅜ
Identity 전략은 기본 키 생성을 database에 위임하는 것으로 알고있고, 거의 대부분의 경우 auto_incr 형식으로 사용하리라 생각하여 작성하였습니다.

문제는 Auto는 DB에 종속적으로 기본키 생성전략을 따라가는 것인데, 
사실 여기서 제가 말한 것은 Auto가 아니라 아예 직접 id를 할당하는 방식을 의도했던 것 같습니다.

GenerationType에는 기본 키를 직접 입력하는 방식은 enum으로 분류되지 않은것 같은데, GenerationType을 nullable하게 관리하거나 아니면 별도 값을 하나 추가 해서 관리하는 방식이 되어야 할 것 같긴 합니다.

혹시 제가 이해한 것이 맞을까요?

2024-10-22 12:38 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        final EntityKey entityKey = new EntityKey((Long) id, clazz);
아 넵넵 이부분은 다시 Serializable로 변경하도록 해야겠네요, 다른 타입의 id를 수용해야할 것 같습니다.

2024-10-22 12:44 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
>          final EntityPersister entityPersister = new EntityPersister(entity.getClass(), jdbcTemplate);
말씀하신것처럼 EntityPersister가 메서드를 실행할때마다 생성하는걸 의식하긴 했었는데요, 
이게 생성자에서 entity를 받으려고 변경되어서 이렇게 된 것 같네요, 기존처럼 build 메서드에서 파라미터를 받으면 하나로 관리할 수 있을 것 같습니다!

추가로 질문이 하나 있는데요, 이게 제가 방향을 잘 잡은건지 모르겠는데, EntityPersister역시 비슷하게 EntityManager의 persist/update/ 마다 생성되고 있어서, 이게 맞는 방향인지도 궁금합니다 :)

2024-10-22 12:46 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        List<String> dirtyColumns = entitySnapshot.getDirtyColumns(persistenceContext.getEntity(entityKey));
제가 구현한것은 변경된 컬럼만 update를 하였군요, 

관리 객체를 조회 후 스냅샷과 비교하여 하나라도 변경된 컬럼이 있다면 -> 전체 컬럼에 대해 update
이것이 말씀하신 의도가 맞을까요?? 😄

2024-10-22 12:48 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
>      public void update(Object entity) {
Hibernate에는 merge 메서드가 제공되는 것으로 알고있습니다. 생각해보면 여기도 merge 형식으로 구현되어야 할 것 같군요!

2024-10-22 12:55 UTC, NamKey commented on README.md
> +      - [x] Auto 전략일때
>Identity 전략은 기본 키 생성을 database에 위임하는 것으로 알고있고, 거의 대부분의 경우 auto_incr 형식으로 사용하리라 생각하여 작성하였습니다.
문제는 Auto는 DB에 종속적으로 기본키 생성전략을 따라가는 것인데,
사실 여기서 제가 말한 것은 Auto가 아니라 아예 직접 id를 할당하는 방식을 의도했던 것 같습니다.

여기까지 설명하신 부분은 정확하십니다! AUTO에 대한 방식이 데이터베이스마다 다를텐데 뭔가 생각하시는게 따로 있는 거 같으셔서 질문드렸습니다 😄
다만 직접할당하는 Strategy를 만드시는 것은 반대입니다! 
왜냐하면 직접 id를 채번하는 것은 동시성 이슈에서 자유로울 수 없고 중복에서도 문제가 발생할 여지가 큽니다!
IDENTITY 방식으로 고도화하는 방향으로 제안드립니다!

2024-10-22 12:55 UTC, NamKey commented on src/main/java/persistence/entity/PersistenceContextImpl.java
> +    public boolean isManagedEntity(Object entity, Object id) {
질문드리는 이유는 
- Managed 라는 JPA entity의 상태(MANAGED, DETACHED, ...)를 포함하여 설계하셨다면 JPA에서의 Managed 상태와 id가 채번된 것은 바라보는 관점이 다릅니다!
- 자체적으로 관리한다는 개념으로 Managed entity 접근하셨다면 추후 4단계에서 진행될 내부 엔티티 상태로 인해 혼동이 오실수도 있을 거 같아 다른 네이밍으로 변경제안드립니다!

2024-10-22 12:56 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        final EntityKey entityKey = new EntityKey((Long) id, clazz);
저는 찬호님이 Serializable로 지정한 타당한 이유가 있다고 생각했었는데 의도하신 것이 이번 미션을 진행하면서 없어지셨던 것일까요? 😄

2024-10-22 12:59 UTC, chanho0912 commented on README.md
> +      - [x] Auto 전략일때
넵! 감사합니다. 해당 방향으로 고민을 조금 더 해보겠습니다 :)

2024-10-22 13:00 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        List<String> dirtyColumns = entitySnapshot.getDirtyColumns(persistenceContext.getEntity(entityKey));
정확하십니다! 👍
찬호님이 구현하려는 방향은 추가되는 기능 관점으로 생각되어서 추상화/책임의 응집 방향으로 리팩토링 해주시면 좋겠습니다!
왜냐하면 EntityManager 는 생각보다 이미 책임이 너무 많은 클래스라고 생각되는데, 메서드에 많은 로직이 들어가는 것을 고려하여 제안드립니다 💪

2024-10-22 13:01 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        final EntityKey entityKey = new EntityKey((Long) id, clazz);
잠깐 밤에 작업하다보니 망각했었나 봅니다...ㅜ 꼼꼼히 봐주셔서 감사합니다 !!

2024-10-22 13:01 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        List<String> dirtyColumns = entitySnapshot.getDirtyColumns(persistenceContext.getEntity(entityKey));
넵 ! 감사합니다 ㅎㅎㅎ 해당 방향으로 고민해보겠습니다 :)

2024-10-22 13:02 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
>      public void update(Object entity) {
더 정확히는 Hibernate는 JPA의 구현체이고 이미 EntityManager에 대한 Spec(인터페이스)이 정의되어 있습니다!
[EntityManager JPA Spec](https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManager.html)

2024-10-22 13:07 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.isManagedEntity(entity, entityPersister.getEntityId(entity))) {
음!! 제가 너무 이상한 생각을 많이 한 것 같네요 ㅜㅜ

```kotlin
fun main(args: Array<String>) {
    Persistence.createEntityManagerFactory("noah").use { emf ->
        emf.createEntityManager().use { em ->
            val transaction = em.transaction
            transaction.begin()

            try {
                val team1 = Team(id = 3, name = "team1")
   
                em.merge(team1)
                transaction.commit()
            } catch (e: Exception) {
                e.printStackTrace()
                transaction.rollback()
            }
        }
    }
}
```
제가 간단하게 테스트를 몇개 해보았는데, 위 경우 insert쿼리가 그대로 실행되어서, merge를 호출하여도 관리되고 있지 않으면 insert를 던지는구나! 생각했습니다.

그런데 말씀하신것처럼 이 과정에서 select가 선행되어 값이 있어야 하는 지 확인해야 할 것 같긴 하네요. 

 ```java
 /**
 * Merge the state of the given entity into the
 * current persistence context.
 * @param entity
 * @return the managed instance that the state was merged to
 * @throws IllegalArgumentException if instance is not an
 * entity or is a removed entity
* @throws TransactionRequiredException if there is no
* transaction when invoked on a container-managed
 * entity manager that is of type
 * PersistenceContextType.TRANSACTION.
*/
 public <T> T merge(T entity);
```

실제 merge의 스펙 문서를 보면 이경우 예외가 맞는 것 같은데
그러면 요구사항이 entityManager.merge()가 호출되었을 때 영속성 컨텍스트를 확인하고, 값이 없다면 예외를 던지는 것이 맞을까요?? :)

2024-10-22 13:08 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
>      public void update(Object entity) {
아 처음부터 해당 문서를 확인하고 구현을 해볼걸 그랬네요 !! 직접 문서 링크까지 공유해주셔서 감사합니다 :)

2024-10-22 13:14 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
>          final EntityPersister entityPersister = new EntityPersister(entity.getClass(), jdbcTemplate);
> 이게 생성자에서 entity를 받으려고 변경되어서 이렇게 된 것 같네요, 기존처럼 build 메서드에서 파라미터를 받으면 하나로 관리할 수 있을 것 같습니다!

오 기대되네요! 혹은 미리 만들어놨다가 캐싱하는 방식으로 구현하실 수도 있을 거 같네요😄

> 추가로 질문이 하나 있는데요, 이게 제가 방향을 잘 잡은건지 모르겠는데, EntityPersister역시 비슷하게 EntityManager의 persist/update/ 마다 생성되고 있어서, 이게 맞는 방향인지도 궁금합니다 :)

윗 질문이랑 같은 것처럼 느껴지는데 두개의 방향으로 설명해보자면
EntityPersister에서 persist/update 시마다 쿼리가 생성되는건 객체의 생명주기상 맞다고 보기 때문에 쿼리가 매번 호출시마다 생기는 것은 맞는 방향이라고 생각합니다.
EntityManager의 메서드 호출시마다 EntityPersister가 생성되는 건 전에 말씀드렸던 역할과 연관지어 생각해보면 어색합니다. `- EntityPersister는 엔터티의 메타데이터와 데이터베이스 매핑 정보를 제공하고, 변경된 엔터티를 데이터베이스에 동기화하는 역할` 

런타임에 메타데이터와 데이터베이스의 매핑정보가 실시간으로 변화하지 않는데 지속적으로 같은 정보를 제공하기 위해서 재성성을 해야될까라는 의문이 남기 때문입니다! 

찬호님은 어떻게 생각하시나요?

2024-10-22 13:14 UTC, chanho0912 commented on src/main/java/persistence/entity/PersistenceContextImpl.java
> +    public boolean isManagedEntity(Object entity, Object id) {
넵넵! 이부분도 제가 잘못 알고 있었던 내용인 듯 합니다. 

저는 단순하게 영속성 컨텍스트에 값이 있다면 관리되고 있는 것 아닌가 하여서 붙이게 되었는데요! hasEntity 와 같은 간단한 메서드명으로 변경하는 것이 좋을 것 같습니다!

2024-10-22 13:15 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
>      public void update(Object entity) {
다만 찬호님 2주차 시간이 얼마남지 않았습니다 😁 
다른 것도 구현해봐야지라는 접근보다는 미션에 필요한 부분만 구현해주셔도 충분합니다!!!

2024-10-22 13:22 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.isManagedEntity(entity, entityPersister.getEntityId(entity))) {
맞습니다! 미션 설명서에 해당 요구사항이 없다면 실제 Spec을 확인해보시는 것도 좋습니다

entityManager의 merge() 어떤 상황에서 호출되는지 따라가다보면 `영속성 컨텍스트를 확인하고, 값이 없다면 예외를 던지는 것`이 어떤 의미인지도 파악하실 수 있으실거에요!

2024-10-22 13:22 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.isManagedEntity(entity, entityPersister.getEntityId(entity))) {
왜 그래야 할지에 대한 찬호님의 생각이 궁금합니다!

2024-10-22 13:24 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityPersister.java
> +        entityKey.bindId(entity);
이부분도 사고의 흐름을 조금 설명드리면...

 ```java
   public EntityKey insert(Object entity) {
        final Object id = getId(tableDefinition, entity);
        tableDefinition.tableId().bindValue(entity, id);               // 직접 할당 전략이면 id를 entity insert전에 id를 심어줘야한다고 생각했었습니다...!

        final String query = new InsertQueryBuilder(entity).build();
        final Long insertedId = jdbcTemplate.insertAndReturnKey(query);
        return createEntityKey(entity, insertedId);
    }
    
    private EntityKey createEntityKey(Object entity, Long id) {
        final EntityKey entityKey = new EntityKey(id, entity.getClass());

        entityKey.bindId(entity);               // 반대로 identity 전략이면 entity에 database에서 반환받은 id를 심어줘야 한다고 생각했어요!
        return entityKey;
    }
```

우선 생각은 커멘트 내용과 같았는데, 이게 이것저것 합쳐지다보니 잘못 된것같네요... ㅜ
말씀하신것처럼 id를 entityKey가 할당할 필요는 없어보입니다! 

지금 보니 entity에 id를 할당해주려면 entity class에 id 필드명, id 타입 과 같은 메타정보가 필요할 것 같은데, tableDefinition과 같은 객체에 해당 역할을 주는 것이  적절하다고 생각되는데, 이것도 한번 고민해보고 수정해보겠습니다 :)

2024-10-22 13:26 UTC, chanho0912 commented on src/main/java/persistence/entity/EntitySnapshot.java
> +                    final Object currentValue = column.hasValue(entity) ? column.getValueAsString(entity) : null;
이부분은 snapshot이 생성된 시점을 snapshotValue라고 하고, 현재 관리되고 있는 엔티티의 값을 currentValue라고 지어 보았는데, 다른 네이밍을 고민해보겠습니다...! 😄

2024-10-22 13:28 UTC, chanho0912 commented on src/main/java/persistence/sql/definition/ColumnDefinition.java
> +    public void bindValue(Object entity, Object value) {
음...!
https://github.com/next-step/jpa-entity-manager/pull/202#discussion_r1810724786
여기에 적은 커멘트 내용과 이어서 생각해보면 별도로 entity에 id를 set해주는 컴포넌트가 하나 있어도 좋을 것 같다는 생각이 드는데, 해당 역할을 별도 클래스로 분리하는 것은 어떨까요...?

2024-10-22 13:35 UTC, NamKey commented on src/main/java/persistence/entity/PersistenceContextImpl.java
> +    public boolean isManagedEntity(Object entity, Object id) {
>영속성 컨텍스트에 값이 있다면 관리되고 있는 것 아닌가 하여서 붙이게 되었는데요!

해당 부분은 Managed 상태에 대한 설명이 맞습니다! id 가 있어서 채번된 상태와 Managed 상태는 다르다고 말씀드리고 싶었습니다 !
(GenerationStrategy마다 다르기 때문에)

2024-10-22 13:39 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
>          final EntityPersister entityPersister = new EntityPersister(entity.getClass(), jdbcTemplate);
넵 이부분도 말씀하신 방향이 더 좋은 것 같습니다.

메타데이터와 매핑정보는 실시간으로 변화하지 않기 때문에 Class타입과 TableDefinition을 내부에 Map형식으로 가지고 있게 된다면 하나만 생성해도 될 것 같은 생각이 드네요!

해당 방향 괜찮을까요!?

2024-10-22 13:40 UTC, NamKey commented on src/main/java/persistence/entity/EntitySnapshot.java
> +                    final Object currentValue = column.hasValue(entity) ? column.getValueAsString(entity) : null;
비교의 기준이 헷갈리는 거 같아 질문드렸습니다!
밖에 전달되는 것이 PersistenceContext로부터 전달받은 값이라는 것을 알고보면 currentValue라는 생각이 드는데 
EntitySnapshot 코드만 보면 생성자로 받는 entity가 관리되는 현재값이고 getDirtyColumn 의 entity가 변경하고자하는 엔티티로 보여졌습니다! 😄

2024-10-22 13:47 UTC, NamKey commented on src/main/java/persistence/sql/definition/ColumnDefinition.java
> +    public void bindValue(Object entity, Object value) {
> entity에 id를 set해주는 컴포넌트가 하나 있어도 좋을 것 같다는 생각이 드는데

해당 역할을 하는 Component가 EntityRowMapper 아닌가라는 의문이 들었습니다!

> 해당 역할을 별도 클래스로 분리하는 것은 어떨까요...?

근본적으로 EntityPersister가 persist 했을 때 entityKey를 반환받기 때문아닐까라는 생각이 들었습니다!
id가 있는 entity를 반환받는다면 entityKey도 생성할 수 있고 값을 주입하는 책임은 EntityRowMapper로 다 응집할 수 있지 않을까라는 생각이 들었습니다!

2024-10-22 13:52 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
>          final EntityPersister entityPersister = new EntityPersister(entity.getClass(), jdbcTemplate);
> 실시간으로 변화하지 않기 때문에 Class타입과 TableDefinition을 내부에 Map형식으로 가지고 있게 된다면 하나만 생성해도 될 것 같은 생각이 드네요!

해당 방향에서 걱정되시는 부분이나 고민되시는 부분이 있으실까요?
(제가 어떤것이 좋은지 얘기드리는 것이 찬호님의 코드 색깔이나 생각의 흐름을 자유롭지 못하게 할까봐 질문으로만 가이드 드리고 있는데 어떤게 좋으실까요? 😄)

2024-10-22 14:13 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
>          final EntityPersister entityPersister = new EntityPersister(entity.getClass(), jdbcTemplate);
음!! 아닙니다. 편하게 가이드 주셔도 좋습니다!! 지금처럼도 생각을 많이 해보게 되어 좋은 것 같고, 확실하게 요구사항을 벗어나거나 로직이 어긋난 부분에 대해서는 말씀해주셔도 좋습니다. 😄

기륭님이 질문 주신 의도를 제가 이해한게 맞는 지 확인차 저도 물음표를 자꾸 드리게 되는 것 같습니다 :)  😄

2024-10-22 14:20 UTC, chanho0912 commented on src/main/java/persistence/sql/definition/ColumnDefinition.java
> +    public void bindValue(Object entity, Object value) {
아 !! 감사합니다 ㅎㅎㅎ 이해되었습니다 :)

2024-10-22 14:29 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.isManagedEntity(entity, entityPersister.getEntityId(entity))) {
음... 이부분은 제가 조금 더 찾아봐야 할 것 같습니다. 

개념적으로는 삭제된 엔티티가 다시 병합된다기 보다는 개념상으로 삭제되었으니 다시 persist를 통해 영속되는 과정을 거쳐야 하는 것이 아닌가? 라는 생각을 했습니다.

구현적으로는
detach상태와 remove상태가 모두 영속성 컨텍스트에서 관리를 더이상 하지 않는 것으로 보이는데, 이 둘의 차이를 명확하게 찾지 못한 것 같습니다.

merge는 준영속 상태의 객체를 영속 상태로 만드는 목적을 가지고 있는데... 문제는 준 영속 상태도 영속성 컨텍스트에서 더이상 관리 하지 않으면 entitymanager가 removed와 detached이 둘을 판단할 수 있어야 하는데, 아직 이 부분의 비밀을 잘 모르겠습니다 ...ㅠ

2024-10-22 14:53 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.isManagedEntity(entity, entityPersister.getEntityId(entity))) {
아 제가 질문을 어렵게 드렸네요!
SimpleJpaRepository의 save()에 persist 와 merge 가 어떻게 분기되는지에 대한 얘기였습니다!

2024-10-22 15:04 UTC, chanho0912 commented on src/main/java/persistence/sql/definition/ColumnDefinition.java
> +    public void bindValue(Object entity, Object value) {
이부분을 구현하면서 궁금점이 생겼는데요...!

> entityKey도 생성할 수 있고 값을 주입하는 책임은 EntityRowMapper로 다 응집할 수 있지 않을까라는 생각이 들었습니다!
이렇게 되면 persist()에서 전달받은 Object와 EntityPersister.insert()에서 반환한 Object가 서로 다른 객체여서 원래 객체의 id는 변경되지 않을 것 같은데 제가 잘못 이해한 것일까요...?

원래 객체의 id도 심어져 있어야 한다고 생각해서 질문을 드리게 되었습니다!

2024-10-22 15:38 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.isManagedEntity(entity, entityPersister.getEntityId(entity))) {
아! 이부분은 id값이 null 혹은 0인지를 확인하고 맞다면 persist, 아니라면 merge를 호출합니다.

2024-10-22 15:44 UTC, chanho0912 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.isManagedEntity(entity, entityPersister.getEntityId(entity))) {
아 그러면 id가 있는 상태에서 호출되었고,
id가 있기 때문에 기존에 저장되어 있던 snapshot과 비교하여 update를 수행하길 의도하는데, 없다면 문제가 있다고 판단한다 

요정도 의미로 이해하면 괜찮을까요 ?!

2024-10-22 16:12 UTC, chanho0912 commented on src/test/java/persistence/sql/dml/query/UpdateQueryBuilderTest.java
> +        assertAll(
이부분은 set column의 순서가 보장되지 않았어서 변경하였는데요 !
LinkedHashMap을 사용하도록 수정하겠습니다~

2024-10-22 16:32 UTC, chanho0912 commented
https://github.com/next-step/jpa-entity-manager/pull/202#discussion_r1810910159

이 부분에서 entity persister에서 id를 object entity에 바인딩하는 형식을 취했는데요, 말씀하신 RowMapper를 통해 database에서 새로 조회하게되면 persist()에서 전달받은 entity와 다른 객체가 될 것 같아서, 우선 이렇게 진행하였는데 의견 부탁드립니다!

그 외 말씀하신 부분은 반영을 해보았는데요! 다시 리뷰 부탁드립니다!

2024-10-23 00:51 UTC, NamKey requested changes
안녕하세요 찬호님 😁
늦은 시간까지 고생하셨습니다! 💪
코멘트 남겼으니 확인부탁드려요!

궁금한 점 있으시면 코멘트와 DM 으로 편하게 연락주세요 😄

2024-10-23 00:51 UTC, NamKey commented on src/main/java/persistence/entity/EntityKey.java
> +        tableDefinition.getTableId().bindValue(entity, this.id);
디미터의 법칙 고민해주시면 좋겠습니다 😄

2024-10-23 00:51 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.isManagedEntity(entity, entityPersister.getEntityId(entity))) {
저는 Spring Data Jpa 말씀드린 것이였습니다. 😄
생각해보면 merge는 병합인데 없는 것에 병합되지 않도록 예외를 던지는 것이 명확합니다.
SimpleJpaRepository에서 엔티티가 isNew인지 판단하여 persist와 merge에 대해서 분기합니다.

![image](https://github.com/user-attachments/assets/bf006852-7a98-49bf-b9bb-7520f6951bcd)

2024-10-23 00:51 UTC, NamKey commented on src/main/java/persistence/entity/EntityPersister.java
> +    private final HashMap<Class<?>, TableDefinition> tableDefinitions;
HashMap 이라는 타입으로 명시하는 것은 변경에 유연하지 않습니다! 적절한 타입으로 변경해주세요!

2024-10-23 00:51 UTC, NamKey commented on src/main/java/persistence/entity/EntityPersister.java
> +    private void putTableDefinitionIfAbsent(Object entity) {
해당 메서드가 존재하는 부분도 쿼리가 수행되어야만 EntityPersister가 관리하는 매핑정보가 존재한다라고 느껴지는데 찬호님은 어떻게 생각하시나요? 😄

2024-10-23 00:51 UTC, NamKey commented on src/main/java/jdbc/JdbcTemplate.java
> +    public long insertAndReturnKey(String sql) {
해당 부분에서 primitive 타입을 사용하신 이유가 있으실까요?

2024-10-23 00:51 UTC, NamKey commented on src/main/java/persistence/sql/definition/ColumnDefinition.java
> +    public void bindValue(Object entity, Object value) {
EntityPersister에서 insert 후에 채번된 ID를 기존 파라미터에 넣는 방향으로 제안드린 것이라서 
파라미터에 들어간 엔티티와 반환한 엔티티가 동일합니다!

2024-10-23 00:51 UTC, NamKey commented on src/test/java/persistence/sql/dml/query/UpdateQueryBuilderTest.java
> +        assertAll(
`"UPDATE HasNullableColumnEntity SET name = null, age = 30 WHERE id = 1;"`
해당 쿼리의 set Column 순서가 계속 바뀌었었나요?
질문드리는 이유는 다음과 같이 쿼리가 잘못생성되는 케이스를 검증할 수 없을거 같아서 질문드린 것이였습니다!

검증문 == assert 를 의미했습니다 😄

```
query = "UPDATE HasNullableColumnEntity SET UPDATE HasNullableColumnEntity SET UPDATE HasNullableColumnEntity SET UPDATE HasNullableColumnEntity SET name = null, name = null, age = 30 WHERE id = 1";

() -> assertThat(query).contains("UPDATE HasNullableColumnEntity SET"),
() -> assertThat(query).contains("name = null"),
() -> assertThat(query).contains("age = 35"),
() -> assertThat(query).contains("WHERE id = 1;")
```

2024-10-23 00:51 UTC, NamKey commented on src/main/java/persistence/entity/EntityPersister.java
> +        if (tableDefinition.tableId().idRequired()) {
AUTO 구현안하기로 했으니 해당부분도 필요없겠네요 😄

2024-10-23 00:51 UTC, NamKey commented on src/main/java/persistence/entity/EntityPersister.java
> +                        Collectors.toMap(
해당 부분 때문에 컬럼의 순서가 보장되지 않겠군요!

2024-10-23 00:51 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (dirtyColumns.isEmpty()) {
현재구조도 DynamicUpdate 인데 의도하신걸까요? 😄

2024-10-23 01:29 UTC, NamKey approved these changes
안녕하세요 찬호님 😄
이전 것이 보이고 있어서 부분적으로만 리뷰를 드렸네요! 🙏
전반적으로 피드백 반영해주셔서 감사합니다!
다음 미션 진행하시면서 반영해주셔도 될 사항들이 코멘트로 남겨져 있어서 3단계는 머지하도록 하겠습니다
고생하셨습니다 👍

2024-10-23 01:29 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +            throw new IllegalArgumentException("Entity already persisted");
스펙을 참고해서 적용해주셨군요 👍 좋습니다!

2024-10-23 01:29 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (!persistenceContext.hasEntity(entity, entityPersister.getEntityId(entity))) {
부정로직은 코드가 많아질수록 잘 보이는 경향이 있어서 다음과 같이 변경하면 추후에 파악하기 편해집니다!
`!persistenceContext.hasEntity -> hasNotEntity`

2024-10-23 01:29 UTC, NamKey commented on src/main/java/persistence/entity/EntityPersister.java
> +    public void copyId(Serializable id, Object to) {
제가 이 부분을 못봤었네요! 🙏
`to` 가 의미하는 것이 entity 겠죠? 명확한 이름으로 바뀌면 좋겠습니다 😄

2024-10-23 01:29 UTC, NamKey commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +        if (entitySnapshot.hasDirtyColumns(persistenceContext.getEntity(entityKey))) {
반영해주셨군요! 👍👍

2024-10-23 01:29 UTC, NamKey commented on src/main/java/persistence/sql/dml/query/UpdateQueryBuilder.java
> +                                        LinkedHashMap::new
LinkedHashMap을 통해서 순서가 보장되겠군요! 👍

2024-10-23 01:29 UTC, NamKey commented on src/main/java/persistence/entity/EntityPersister.java
> +        return DEFAULT_ID_VALUE;
생각해보면 만약 같은 엔티티에 대해서 여러개를 생성하여 영속성 컨텍스트에 넣으면 어떻게 될까요? 😄

2024-10-23 01:30 UTC, merged