1단계 - EntityPersister 구현
next-step/jpa-entity-manager pull request #204
Opened 2024-10-22 09:22 UTC by jshans40

안녕하세요 리뷰어님 !! 
처음에 감이 잘 오지 않아서 시간이 오래 걸렸네요 😓
리뷰 잘 부탁드립니다~ 😄

2024-10-22 13:08 UTC, Hyunta requested changes
안녕하세요 상혁님,
1단계 미션 진행하시느라 고생 하셨습니다👍🏻
몇가지 커멘트 남겨드렸는데 확인 부탁드려요.

2024-10-22 13:08 UTC, Hyunta commented on src/main/java/jpa/EntityInfo.java
> +    }
equals를 재정의하실 땐 hashcode도 같이 재정의 해주세요

https://tecoble.techcourse.co.kr/post/2020-07-29-equals-and-hashCode/

2024-10-22 13:08 UTC, Hyunta commented on src/main/java/jpa/EntityPersister.java
> +    <T> T find(Class<T> clazz, Object id);
> - EntityPersister는 엔터티의 메타데이터와 데이터베이스 매핑 정보를 제공하고, 변경된 엔터티를 데이터베이스에 동기화하는 역할

find는 다음 단계를 진행하시면서 EntityLoader에 구현해주시면 됩니다.

2024-10-22 13:08 UTC, Hyunta commented on src/main/java/persistence/sql/model/EntityId.java
> +    }
현재 구조는 EntityId 객체에서 EntityColumnName을 만들어주고 있는 것으로 보여집니다.
현재는 ID 값도 동일하게 EntityColumnName으로 관리하고 있는데,
EntityId를 별도의 도메인으로 관리하는 것은 어떻게 생각하시나요?

2024-10-22 13:08 UTC, Hyunta commented on src/main/java/jpa/EntityPersisterImpl.java
> +    private final JdbcTemplate jdbcTemplate;
EntityPersister 테스트 코드도 작성 부탁드립니다.

2024-10-22 13:08 UTC, Hyunta commented on src/main/java/jpa/EntityPersisterImpl.java
> +    }
EntityPersister의 CUD 기능의 구조가 어느정도 잡혔네요.
메서드를 호출할 때 마다 매번 Query 객체를 생성해줘야 하는데 재사용하도록 구조를 개선해보면 어떤가요?

2024-10-23 14:02 UTC, jshans40 commented on src/main/java/persistence/sql/model/EntityId.java
> +    }
EntityID는 별도의 도메인으로 관리하는게 응지도 측면에서 좋아보입니다~!
따로 분리하겠습니다~

2024-10-23 14:11 UTC, jshans40 commented on src/main/java/jpa/EntityPersister.java
> +    <T> T find(Class<T> clazz, Object id);
아! 넵~ find관련된건 EntityLoader의 역할이군요..

2024-10-23 15:27 UTC, jshans40 commented on src/main/java/jpa/EntityPersisterImpl.java
> +    }
재사용할수있도록 구조를 개선하면 좋을것 같습니다~~!

2024-10-24 12:42 UTC, Hyunta commented on src/main/java/persistence/sql/model/EntityId.java
> +    }
미션을 계속 진행하시면서 필요하실 때 고려해보시는 것도 좋을 것 같습니다ㅎㅎ

2024-10-24 12:42 UTC, Hyunta commented on src/main/java/jpa/EntityPersisterImpl.java
> +    }
싱글턴패턴으로 풀어주셨네요ㅎㅎ👍🏻

2024-10-24 12:47 UTC, Hyunta approved these changes
안녕하세요 상혁님,
피드백 반영 잘 해주셨네요👍🏻
find 관련된 피드백은 다음 단계를 하시면서 자연스럽게 분리될 것 같네요ㅎㅎ
다음 단계도 화이팅 입니다!

2024-10-24 12:47 UTC, merged