Step4
next-step/jpa-entity-manager pull request #239
Opened 2024-11-03 14:10 UTC by min-queue

2024-11-04 13:21 UTC, jwee0330 requested changes
안녕하세요 민규님 🙂
step4 구현 잘 해주셨습니다
소소한 코멘트 남겨 놓았습니다
확인하고 다시 구현 부탁드립니다 🙇🏻‍♂️

2024-11-04 13:21 UTC, jwee0330 commented on src/main/java/persistence/defaulthibernate/DefaultPersistenceContext.java
> +        entityEntry.computeIfAbsent(clazz, k -> new ConcurrentHashMap<>()).put(object, EntityEntry.status(EntryStatus.MANAGED));
EntitySnapShot 과 Entity 저장할때 EntityEntry 까지 함께 저장하면 문제가 생길 것 같습니다.
지금 persist 로직을 보면 db 쿼리 가 다 수행된 뒤 persistenceContext 의 add 가 실행되는데, 과연 entity 의 상태가 추적이 잘 될까요? 강의에서 다룬 내용을 복기해보면 SAVING 상태로 먼저 변경되고 insert 쿼리가 수행된 뒤 MANAGED 상태로 되어야 할 것 같습니다

2024-11-04 13:21 UTC, jwee0330 commented on src/main/java/persistence/defaulthibernate/EntryStatus.java
> +    SAVING // 영속성 컨텍스트에 저장되거나 추가되기 위한 과정 중에 있는 상태
현재 SAVING 상태는 아예 사용되고 있지 않는데요,

SAVING 상태는 엔티티가 현재 저장 중인 상태를 뜻합니다. session.save() 또는 session.persist() 메서드가 호출될 때 
일시적으로 SAVING 상태로 전환되며, 데이터베이스에 새로 합입 중인 엔티티를 나타냅니다.
저장이 완료되면 MANAGED 상태로 전환되도록 구현해 주세요!

2024-11-04 13:21 UTC, jwee0330 commented on src/main/java/persistence/defaulthibernate/EntryStatus.java
> +    LOADING, // 데이터베이스에서 조회중인 상태
LOADING 상태도 엔티티가 데이터베이스에서 로드되고 있는 상태를 나타냅니다.
session.get() 또는 session.load() 같은 메서드를 호출할 때 엔티티가 아직 완전히 초기화되지 않은 경우 일시적으로 LOADING 상태가 됩니다.
로드가 완료되면 MANAGED 상태로 전환됩니다.

1차 캐시 구현도 결국 MANAGED 상태로만 영속화된 엔티티들의 상태를 관리 할 수 있을것으로 기대합니다

2024-11-07 12:46 UTC, jwee0330 requested changes
안녕하세요 민규님 🙂
EntityEntry 구현도 잘 해주셨네요!
다만 EntityEntry 의 역할이 아직 조금 부족하다고 느껴지네요,
조금 더 잘 만들어주신 EntityEntry 를 활용해 보면 좋을 것 같아요
활용에 대한 예시는 코멘트로 남겨놓을게요!
피드백 확인하고 수정하신 뒤 다시 PR 요청 부탁드립니다 🙇🏻‍♂️

2024-11-07 12:46 UTC, jwee0330 commented on src/main/java/persistence/defaulthibernate/EntityEntry.java
> +    }
사용되고 있지 않네요? 🥲

2024-11-07 12:46 UTC, jwee0330 commented on src/main/java/persistence/defaulthibernate/DefaultPersistenceContext.java
> +    }
EntityEntry 는 set 만 하시나요?
EntityEntry 를 가져와서 MANAGED 라면 바로 entitySnapshotsByKey 에서 스냅샷을 반환해줘도 좋을것 같은데요?
EntityEntry에 아직 책임이 부족하다고 느끼는데 민규님은 어떻게 생각하세요?

2024-11-07 12:46 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityKey.java
> +}
개행 빠져있네요ㅎㅎ

2024-11-07 12:46 UTC, jwee0330 commented on src/main/java/persistence/entity/impl/DefaultEntityManager.java
> +        defaultPersistenceContext.setEntityEntryStatus(entityKey, EntryStatus.SAVING);
음 먼저 EntityEntry 가 존재하는지 확인해 보는게 먼저 아닐까요?
없으면 SAVING 상태로 생성하고 
이미 존재한다면 EntryStatus 를 통해서 validation 이 추가 될 수도 있을것 같아요~
이미 GONE 상태의 Entity 라면? persist 해도 될 까요?
EntityEntry 를 활용해서 PersistenceContext 에서 엔티티의 생명주기를 관리의 정합성 맞추는데 도움을 주는 역할로 활용해 주셨으면 좋겠습니다!

2024-11-09 07:29 UTC, jwee0330 approved these changes
안녕하세요 민규님 🙂
피드백 반영하느라 고생 많으셨습니다!
저와 함께한 EntityManager 미션 기간동안 많은 인사이트 얻는데 조금이나마 도움이 되셨기를 바라 봅니다 😁
다음 단계도 파이팅하세요 💪🏼

2024-11-09 07:29 UTC, jwee0330 commented on src/main/java/persistence/defaulthibernate/DefaultPersistenceContext.java
> +        entityEntries.put(entityKey, entry);
여기서 MANAGED 로 EntityEntries 에 보관을 하는데
PersistenceContext.add 를 호출하는 EntityManager 에서 add호출 이후에 또 entityEntry를 MANAGED 로 set 하는 부분이 있네요.. 중복적인 행위가 있는것이 조금 어색하긴 하네요 🥲
추후 개선 포인트로 가져가 보셔도 좋을것 같아요

2024-11-09 07:30 UTC, merged

2024-11-09 11:00 UTC, min-queue commented on src/main/java/persistence/defaulthibernate/DefaultPersistenceContext.java
> +        entityEntries.put(entityKey, entry);
넵알겠습니다 감사합니다 리뷰어님!