🚀 4단계 - EntityEntry
next-step/jpa-entity-manager pull request #255
Opened 2024-11-12 16:03 UTC by wenodev

마지막 4단계 진행했습니다 ㅎㅎ
감사합니다 ㅎㅎ

2024-11-13 00:53 UTC, NamKey requested changes
안녕하세요 주원님 😄

새로 추가된 부분과 더불어 필요한 부분들에 대해 코멘트 남겼으니 확인부탁드립니다!
확인 후 재요청 주세요 🙇‍♂️

2024-11-13 00:53 UTC, NamKey commented on src/main/java/persistence/sql/entity/PersistenceContext.java
> +        return entry.getValue().isDirty() &&
`getValue().isDirty()`에 디미터의 법칙을 적용하는 것을 제안드립니다!

2024-11-13 00:53 UTC, NamKey commented on src/main/java/persistence/sql/entity/Status.java
> +public enum Status {
요구사항에 주어진 Status는 다음과 같은데 상태를 특정 상태들을 생략하신 이유가 있으실까요? 😄
```
public enum Status {
	MANAGED,
	READ_ONLY,
	DELETED,
	GONE,
	LOADING,
	SAVING
}
```

`NEW` 라는 상태를 보았을 때는 Entity의 상태를 사용하신 것으로 보여지는데, 현재 과제에서 주어진 상태는 Hibernate 내부에서 사용하는 상태입니다!

2024-11-13 00:53 UTC, NamKey commented on src/main/java/persistence/sql/entity/PersistenceContext.java
> +                .filter(this::isDirtyAndManagedEntity)
현재구조상 `getDirtyEntities`를 호출하면 dirty필드가 항상 false이므로 항상 비어있는 Map이 기대됩니다!

2024-11-13 00:53 UTC, NamKey commented on src/main/java/persistence/sql/entity/Session.java
> +            persistenceContext.removeEntity(key);
removeEntity도 실패한다면 persistenceContext에 entity가 그대로 남아있을것으로 기대됩니다!

2024-11-13 00:53 UTC, NamKey commented on src/main/java/persistence/sql/entity/Session.java
> +        } catch (final Exception e) {
어떤 Exception이 명시적으로 발생할지 결정되면 좋을것 같습니다!

2024-11-13 00:53 UTC, NamKey commented on src/main/java/persistence/sql/entity/Session.java
> +                entityPersister.update(entity);
`flush()`에서는 DirtyChecking을 통한 Update 뿐만 아니라 Insert도 수행된다는 점도 기억해주세요 😄

2024-11-13 00:53 UTC, NamKey commented on src/main/java/persistence/sql/entity/PersistenceContext.java
> +                .filter(this::isDirtyAndManagedEntity)
해당 Entity가 dirtyEntity인지 어떻게 판단하는지만 구현되면 좋을것 같습니다!

2024-11-15 10:32 UTC, wenodev commented
피드백주신 부분 최대한 반영해봤습니다!
추가적으로 그 전에는 flush를 제외한 메서드에서도 DB의 변경을 일으켰는데, flush에서만 DB에 변경을 일으키도록 수정해봤습니다!

혹시 놓친부분있다면 말씀해주세요! 감사합니다!

2024-11-15 15:28 UTC, NamKey requested changes
안녕하세요 주원님! 😄
4단계 진행은 요구사항에 모두 부합하게 완료해주셨네요 💯
추가적으로 확인이 필요한 부분에 대해 코멘트 남겼으니 확인부탁드립니다
궁금하신 점이나 고민이 있으시다면 코멘트나 DM으로 요청주세요!

2024-11-15 15:28 UTC, NamKey commented on src/main/java/persistence/sql/entity/EntityLoader.java
> +        return id + 1;
AUTO_INCREMENT라고 해도 항상 1씩 증가하지 않을수 있다는 점도 기억해주세요!
해당 부분은 DB와 관련된 부분이여서 현재 이런 구현으로 충분하다고 생각합니다 😄

2024-11-15 15:28 UTC, NamKey commented on src/main/java/persistence/sql/entity/PersistenceContext.java
> +    void prePersist(final Object entity, final Object primaryKey) {
요구사항에서 주어진 상태들을 모두 반영해주셨군요! 👍

2024-11-15 15:28 UTC, NamKey commented on src/main/java/persistence/sql/entity/Session.java
> +        if (currentStatus == Status.DELETED || currentStatus == Status.GONE) {
삭제될 수 없는 상태 부분도 처리해주셨군요! 💯

2024-11-15 15:28 UTC, NamKey commented on src/main/java/persistence/sql/entity/Session.java
> +
이전에도 코멘트 드렸듯이 `getDirtyEntities()`에서 `isDirtyAndManagedEntity()` 는 isDirty 값이 모두 false 기 때문에 getDirtyEntites()에서 나오는 Map 은 비어있으므로 insert, update가 수행되지 않겠네요!

``` java
return entityCache.entrySet().stream()
                .filter(this::isDirtyAndManagedEntity)
                .collect(toCacheKeyObjectMap());
```

dirtyCheckTest 에서 `persist()`와 `flush()`를 호출하더라도 실제로 데이터베이스에는 아무값도 저장되지 않고 PersistenceContext에 저장 / 불러오기 되어 테스트가 통과하는 것으로 보입니다!

2024-11-17 02:10 UTC, wenodev commented on src/main/java/persistence/sql/entity/EntityLoader.java
> +        return id + 1;
현재 요구사항은 만족하니 추가적인 수정사항은 없어도 된다는 의견이실까요?!

2024-11-17 02:12 UTC, wenodev commented on src/main/java/persistence/sql/entity/Session.java
> +
네네 그러네요!
더티체크는 snapshot을 만들어서 다시 구현해봤습니다!

2024-11-17 02:12 UTC, NamKey commented on src/main/java/persistence/sql/entity/EntityLoader.java
> +        return id + 1;
네 맞습니다!

2024-11-17 02:14 UTC, wenodev commented
기존에 있던 EntityEntry를 삭제하고 EntityState를 생성하여 1차 캐싱과 버전관리 및 더티체킹을 하도록 수정했습니다!
꼼꼼하게 봐주셔서 감사합니다!
추가적으로 부족한 부분있으면 말씀해주세요!

2024-11-17 02:22 UTC, NamKey commented on src/main/java/persistence/sql/entity/CacheEntry.java
> +    private boolean isFieldDirty(final Field field) {
제가 생각했던 구현내용이였습니다! 👍👍

2024-11-17 02:22 UTC, NamKey commented on src/main/java/persistence/sql/entity/CacheEntry.java
> +            if (isPersistentField(field)) {
해당 부분 if 문을 2depth로 놓을 필요가 없다고 생각드네요 리팩토링 부탁드려요! 😄

2024-11-17 02:22 UTC, NamKey commented on src/main/java/persistence/sql/entity/EntityState.java
> +        return status == Status.MANAGED && cacheEntry.isDirty();
항상 MANAGED 상태여야지만 isDirty가 `true`가 나올 수 있으므로 저장되지 않은 상태의 Entity는 항상 false로 나와서 insert가 수행되지 않을것으로 예상됩니다!

2024-11-18 01:42 UTC, NamKey requested changes
안녕하세요 주원님! 😄
DM으로도 전달드렸지만 
추가적인 코멘트 확인하셔서 재요청부탁드립니다! 💪

2024-11-18 05:21 UTC, NamKey approved these changes
안녕하세요 주원님 😄
바쁘신 와중에도 4단계 마무리와 더불어 디테일함까지 챙겨주시느라 고생많으셨습니다! 💯
이번에 진행했던 미션들에서는 JPA 의 전반적인 구조와 동작방식에 대해서 얻으시길 바라면서 가이드를 드렸는데 배움이 있으셨길 바라면서 다음으로 넘어가시죠 🚀
고생하셨습니다 💪

2024-11-18 05:21 UTC, NamKey commented on src/main/java/persistence/sql/entity/EntityState.java
> +        if (status == Status.DELETED || status == Status.GONE) {
상태별로 같은 응답이라면 EnumSet을 사용하여 처리하시는 것도 좋을 것 같습니다!
추가적인 제안이라면 이런 케이스들 (실제로는 원하는대로 동작하지 않았지만 기존 테스트 케이스가 통과하는 케이스) 을 어떻게 감지할 수 있는 테스트코드를 작성할까 고민해보시면 코드 뿐만 아니라 테스트 코드 퀄리티도 더 높일 수 있다는 점 기억해주세요 😄

2024-11-18 05:22 UTC, merged