[2주차 - Step 2] 엔터티 초기화 (EntityLoader) PR 입니다.
next-step/jpa-entity-manager pull request #33
Opened 2023-10-24 22:39 UTC by jongmin4943

`EntityLoader` 를 구현했는데 일단 find 메서드에서 계속 new 를 해서 생성하는 방식이 되었습니다.
제네릭을 쓰려다보니 미리 객체를 만들어서 Map 에 담아두려니 좀 지저분해져서 일단 이렇게 만들어 놓고 피드백 받아보려합니다!제네릭을 안쓰려면 강제 형변환 하는 코드가 들어가야할것같은데 어떤 방향이 나을지 고민하다가 PR 보내봅니다.

이번 리뷰도 잘 부탁드립니다!.

2023-10-25 17:57 UTC, leeyohan93 requested changes
안녕하세요 종민님 :)
2주차 단계도 잘 구현해주셨네요! 💯 
질문에 대한 답변과 다음 단계로 넘어가기 전에 고민해볼만한 부분을 코멘트로 남겨두었으니 확인 부탁드려요
이제 목요일이고 주말이 얼마 남지 않았네요! 
화이팅입니다 🔥

2023-10-25 17:57 UTC, leeyohan93 commented on src/test/java/persistence/entity/EntityLoaderTest.java
> +class EntityLoaderTest {
> 아 그리고 EntityLoader 에서 객체를 load 하는 메서드를 테스트하는것에 고민을 많이 했었습니다. MockJdbcTemplate 에서 queryForObject 를 override 해서 ResultSet 을 원하는 형태로 강제로 내뱉는걸 하다가 좀 아닌거같아서 포기하고 결국 일단 select 문만 테스트하고 말았습니다. 테스트가 어려워지면 형태가 안좋은 형태의 징조라는 말을 들은적이 있어서.. 어떻게 해야할까요?

실무를 하다보면 이런 테스트를 많이 만나 보셨을 거라 생각하는데요! 😄 

제가 생각하는 개인적인 테스트에 대한 부분을 공유드려보겠습니다 :)
결론부터 이야기하자면 MockJdbcTemplate에서 queryForObject()의 override 하여 응답 값을 확인하는 정도로만 테스트할 것 같은데요 ㅎㅎ 

EntityLoader는 아래 두 책임을 가진 객체들과 협력하여 순차적으로 실행해주는 역할을 하고 있기 때문에 queryForObject()의 결과로 엔티티를 확인하는 것으로 어느정도 충분하다고 생각합니다! 😄 
- 쿼리를 만든다
- 쿼리를 통해 엔티티를 반환한다

다른 방법으로는 Mock이 아닌 실제 구현체로 통합테스트를 작성하는 방법도 있을 것 같아요! 👍

2023-10-26 00:09 UTC, jongmin4943 commented on src/main/java/persistence/core/EntityMetadata.java
> +                        .collect(Collectors.toUnmodifiableList()));
코드를 적다가 습관적으로 적은 것 같습니다. 객체 내에서 내부필드에 접근할때 this 를 생략하는게 더 낫나요?

2023-10-26 00:22 UTC, jongmin4943 commented on src/main/java/persistence/core/PersistenceEnvironment.java
>      }
> 엔티티 매니저의 EntityMetadata 가 되어가고 있는 것 같아요

`EntityManager` 가 `EntityMetadata` 에 의존적인 구조를 가져가는 것 같다는 말씀이실까요?

> 지금 구현 상황에서 꼭 필요한 부분일지 고민해보시면 좋을 것 같습니다!

저는 이 객체를 처음 구동할때 필요한 객체들을 관리하는 주체로 생각하고 있는데요. 이 부분이 없다면 Application 이 구동되는 최상위에서 생성해서 주입받아 사용하는 방식을 생각하면 될까요?

2023-10-26 00:26 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityLoader.java
> +    private final EntityPersister entityPersister;
> EntityPersister는 엔터티의 메타데이터와 데이터베이스 매핑 정보를 제공하고, 변경된 엔터티를 데이터베이스에 동기화하는 역할

미션 내용중에 `EntityPersister` 가 엔터티의 정보를 제공한다고 되어있어서 상태로 넣고 getter 를 이용해 정보를 받아오는 구조로 짰습니다. `EntityLoader` 도 `EntityMetadata` 를 이용해 필요한 상태를 `EntityPersister` 처럼 상태로 가지고 있는게 나을까요?

2023-10-26 00:28 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityPersisterProvider.java
>  public class EntityPersisterProvider {
> EntityPersisterProvider 또한 서버가 실행 될 때 한번만 실행하는 것처럼 EntityPersisterProvider 또한 같은 방식으로 실행되면 된다고 생각합니다 :)

이 부분은 앞의 부분이 `EntityLoaderProvider` 라고 생각하면 될까요?

2023-10-26 00:29 UTC, jongmin4943 commented on src/test/java/persistence/entity/EntityLoaderTest.java
> +class EntityLoaderTest {
감사합니다! Override 하는 형태로 바꿔보겠습니다!

2023-10-26 02:27 UTC, leeyohan93 commented on src/main/java/persistence/entity/EntityPersisterProvider.java
>  public class EntityPersisterProvider {
앗 오타가 있었군요 😢  앞의 부분은 `EntityManagerFactory ` 라고 생각해주시면 될 것 같습니다!

2023-10-26 02:31 UTC, leeyohan93 commented on src/main/java/persistence/core/EntityMetadata.java
> +                        .collect(Collectors.toUnmodifiableList()));
저는 개인적으로 아래 생성자 예시에서 사용하는 것처럼 this 는 같은 이름의 변수가 여러 개 존재할 때, 현재 클래스의 변수를 가리키는 용도로만 사용하고 있어요! 
```
Sample(String name) {
    this.name = name;
}
```

일반적인 상황에서 this 를 붙이면 다른 개발자들이 볼 때 같은 변수 이름에 접근하는 변수가 있나? 라고 생각이 될 수 있을 것 같아 생략할 수 있다면 생략하는게 좋다고 생각합니다! 개인적인 의견이니 참고만 해주세요 😄

2023-10-26 02:59 UTC, leeyohan93 commented on src/main/java/persistence/entity/EntityLoader.java
> +    private final EntityPersister entityPersister;
> 미션 내용중에 EntityPersister 가 엔터티의 정보를 제공한다고 되어있어서 상태로 넣고 getter 를 이용해 정보를 받아오는 구조로 짰습니다.

미션의 내용을 보고 `EntityPersister`가 매핑 정보를 제공하기 때문에 gettter를 통해 구현해주신거군요 👍 
`EntityPersister` 가 엔터티의 정보를 제공을 모두 담당한다고 하면 아래와 같은 상태로 만들어 getter를 사용하지 않고 구현해볼 수도 있을 것 같습니다!
- EntityPersister 내부에 EntityLoader 를 상태로 가지고 있는 상태

> EntityLoader 도 EntityMetadata 를 이용해 필요한 상태를 EntityPersister 처럼 상태로 가지고 있는게 나을까요?

저는 개인적으로 이 방법도 나쁘지 않다고 생각하는데요. `EntityLoader` 와 `EntityPersister` 모두 클래스의 이름과 같게 온전히 책임을 다하면서 역할이 분리되어있기 때문이라고 생각합니다 :) 

제가 이야기드린 방법들은 참고만 해주시고 정답은 없으니 종민님이 고민해보시고 종민님의 기준에 맞게 설계를 개선해주셔도 좋을 것 같습니다 😄

2023-10-26 03:02 UTC, leeyohan93 commented on src/main/java/persistence/core/PersistenceEnvironment.java
>      }
> EntityManager 가 EntityMetadata 에 의존적인 구조를 가져가는 것 같다는 말씀이실까요?

제가 이해하기 어렵게 이야기드렸네요 😢 
`EntityMetadata ` 가  `Entity 클래스`의 관련된 정보들을 모아서 함께 제공하 듯
`PersistenceEnvironment ` 또한 `EntityManger` 의 관련된 정보들을 모아서 함께 제공하는 것 같다는 이야기였습니다!

> 저는 이 객체를 처음 구동할때 필요한 객체들을 관리하는 주체로 생각하고 있는데요. 이 부분이 없다면 Application 이 구동되는 최상위에서 생성해서 주입받아 사용하는 방식을 생각하면 될까요?

네 맞습니다. EntityManger를 생성할 때 EntityPersister, EntityLoader 를 주입받아 사용한다고 생각해보면 어떨까요? 🤔

2023-10-26 09:01 UTC, jongmin4943 commented on src/main/java/persistence/core/PersistenceEnvironment.java
>      }
반영 완료 - [`77ac0c3`](https://github.com/next-step/jpa-entity-manager/pull/33/commits/77ac0c3fe2521274bfa42322a4c602d91d940d60)

2023-10-26 09:03 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityLoader.java
> +    private final EntityPersister entityPersister;
EntityLoader 도 EntityMetadata 를 이용해 필요한 상태를 EntityPersister 처럼 상태로 가지고 있는게 만들었습니다.

반영 완료 - [`b5fe1b8`](https://github.com/next-step/jpa-entity-manager/pull/33/commits/b5fe1b85e59c91c7ae0d223c2ad346c301f9bdb1)

2023-10-26 09:03 UTC, jongmin4943 commented on src/test/java/persistence/entity/EntityLoaderTest.java
> +class EntityLoaderTest {
반영완료 - [`fb9b2fd`](https://github.com/next-step/jpa-entity-manager/pull/33/commits/fb9b2fdf7a8d8e4342a416e903b0c0c80e16144f)

2023-10-26 09:05 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityPersister.java
> +    private final EntityColumns insertableColumns;
요구사항 구현의 집중을 위해 위해 일단 커넥션 생각은 안하기로 했습니다.

반영 완료 - [`dc900f8`](https://github.com/next-step/jpa-entity-manager/pull/33/commits/dc900f85d2ee7481831ea0f7a098dcae0a688a4c), [`0016a7f`](https://github.com/next-step/jpa-entity-manager/pull/33/commits/0016a7fad8a195e88102a2ae2584d0c28c6bde1f)

2023-10-26 12:29 UTC, leeyohan93 approved these changes
안녕하세요 종민님 😄 
단계를 진행하며 많은 고민과 도전을 하시느라 너무 고생하셨습니다 🙏 
이번 단계는 여기서 머지하도록 하겠습니다.
사소한 코멘트를 남겨두었으니 확인 해주시고 다음 단계도 화이팅입니다 🔥 🚀

2023-10-26 12:29 UTC, leeyohan93 commented on src/main/java/persistence/entity/EntityLoader.java
> +    }
지금 구현도 너무 좋지만 entityMetadata 를 객체의 상태로 가지지 않는 만큼 `EntityLoader` 에서는 `EntityMetadata`로 향하는 의존성을 극단적으로 줄 수도 있을 것 같습니다 :) 

EntityMetadataProvider의 위치는 조금 고민이 되는데요. EntityManger 도 Provider가 있었다면 적절한 위치가 될 수도 있을 것 같은데 종민님 의견도 궁금합니다 😄

2023-10-26 12:29 UTC, merged

2023-10-26 13:21 UTC, jongmin4943 commented on src/main/java/persistence/entity/EntityLoader.java
> +    }
저도 비슷한 느낌을 받아서 생각의 방향을 EntityManagerFactory 비슷한것을 만드는것으로 해보고 도전해봤습니다. 하다보니 Factory 에서 EntityManager 생성시 어떤값을 주입해줘야하나 고민이 많이 되더라고. 그러다 일단 구현시간이 좀 촉박하다 느껴져서 패스했습니다. 구현 중 시간이 나면 한번 구현해보겠습니다!