[3-2단계] - Snapshot 관련 구현
next-step/jpa-entity-manager pull request #59
Opened 2023-10-31 07:08 UTC by zinzoddari

정원님 안녕하세요 🥹
뒤에 더 많은 어려운 단계들이 있겠다만, 스냅샷 만들기 하다가 정말 눈물 찌이이일끔 흘린 것 같아요 ㅋ.ㅋ..ㅋ...

메타데이터를 사용하지 못하는 영속성 컨텍스트 부분에서는 어떻게 값을 비교할 것인가
메타 데이터는 이미 persister 부분에 있는데, 등등 구조부터가 잘못된건가 많은 고민을 했던 것 같아요.

저도 깊은 복사를 해야할 수 밖에 없던 경우가 있었는데, 강의 때 깊은복사까지는 하지 않아도 된다고하여
디비에서 계속 불러오는 형식으로 구현을 해 보았고, insert는 결국 바로 select를 해주기 위해서 바로 저장을 하는 형태로 구현을 했지만
update나 delete의 경우 나중에 entityManager의 flush()를 통해서 바뀐 점을 비교해서 update인지 delete인지 구분을 나름 해 주었습니다.

다들 영속성 컨텍스트랑 persister는 어쩔 수 없이 밀접 관계가 있을 수 밖에 없다고 얘기를 해주시는데
인자로 persister를 넘겨 영속성 컨텍스트 내부에서 DB 조회를 하는 모습은 아직도 낯선 것 같습니다 🥹

항상 매번 감사드립니다 ( _ _ ) 이번 PR도 잘 부탁 드리겠습니다 🙏🏻

2023-10-31 16:14 UTC, jwee0330 requested changes
안녕하세요 진주님 :)
3단계 구현에 대한 피드백을 반영해 주셨군요 :)
몇가지 수정 요청 드렸는데 고민해 보시고 반영하신 후 다시 리뷰 요청 부탁드립니다 🙏🏻
논의가 필요한 부분이 있다면 DM 보내주세요🙂

2023-10-31 16:14 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityManagerImpl.java
>      }
다시 보니 EntityManager 에 update 메소드는 요구사항에 없네요🥲
update 메소드는 제거하고!
find 로 찾은 객체의 값이 변경하고 flusth 호출할 때 자연스럽게 update 쿼리가 발생 하도록 수정해 볼까요?😄

2023-10-31 23:07 UTC, zinzoddari commented on src/main/java/persistence/entity/EntityManagerImpl.java
>          }
나름 중복을 방지하고자 해당 영속성 컨텍스트에 동일 엔티티가 있다면, 이미 앞서 저장 혹은 조회가 되었기에 exception을 터뜨려주는게 안전하지 않을까? 싶었습니다 🥲 근데 밑에 별도 update가 없더라면... 이 부분은 없어지는게 맞을 것 같아요!

2023-11-02 03:26 UTC, jwee0330 requested changes
진주님 안녕하세요🙂
피드백 반영 잘 해주셨네요 👍 
몇가지 코멘트 남겼는데 확인하시고 수정 하시어 다시 리뷰요청 부탁드립니다🙏🏻
업무가 바빠 힘드시겠지만 끝까지 파이팅 입니다 💪

2023-11-02 03:26 UTC, jwee0330 commented on src/main/java/domain/Snapshot.java
> +        }
예외를 잡아서 로직처리를 하는건 프로그램 오작동의 위험이 있습니다🥲
예외 처리를 확실하게 수정해주세요

2023-11-02 03:26 UTC, jwee0330 commented on src/main/java/persistence/entity/PersistenceContextImpl.java
> +        contextMap.put(key, new Snapshot(id, entity));
현재는 entity 가 null 인 상황에서도 contextMap.put 하는 상황이 발생하는데요
entity 가 null 이라면 addEntity 자체가 수행되지 않거나
수행 되더라도 put 호출 전에 return 되는게 좋겠어요 :)

2023-11-02 03:26 UTC, jwee0330 commented on src/main/java/persistence/entity/PersistenceContextImpl.java
> +    }
SnapShotMap 에 존재 할때는 null 이 응답되는 걸까요? 🤔
혹시 설명을 좀 부탁드려도 될까요?

2023-11-02 03:26 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +            getPersister(t.getClass()).insert(t);
진주님 저희 flush 사용하기로 했으니까 persist 도 flush 되는 순간 저장되도록 수정해 보는게 어떻까요? 😁

2023-11-02 03:26 UTC, jwee0330 commented on src/main/java/persistence/entity/EntityManagerImpl.java
> +    public void flush() {
트랜잭션 사용 안하다 보니 flush 로 처리하시는 개념이 너무 좋네요 👍 
다만 association 단계에서 힘들어 지실수 있어서 걱정입니다🥲
이번 단계를 어떻게 가져가야 할지 DM을 통해 대화 해보는게 좋을것 같아요

2023-11-02 16:05 UTC, zinzoddari commented on src/main/java/persistence/entity/PersistenceContextImpl.java
> +        contextMap.put(key, new Snapshot(id, entity));
put 전에 entity가 null인지 확인하고 return 할 수 있도록 검증 로직 추가 하였습니다 : )

2023-11-02 16:12 UTC, zinzoddari commented on src/main/java/persistence/entity/PersistenceContextImpl.java
> +    }
별도 트랜잭션을 신경쓰지 말라고 하셨지만, 구현 할 때 트랜잭션을 생각하고 구현을 했던 것 같습니다
한 트랜잭션에서 영속성 컨텍스트가 생기기 때문에 뭔가... 최초 값 한 번 조회하고 이후에는 덮어쓸 일이 없을거라 생각했는데, 지금 상태에서는 해당 부분은 제외하고 구현하는게 맞다 판단이 들어 이 부분은 제거 하였습니다

2023-11-03 11:46 UTC, jwee0330 approved these changes
안녕하세요 진주님
전체적으로 피드백 잘 반영해 주셨네요🙏🏻
3단계는 이만 머지 하도록 하겠습니다 :)
4단계 EntityEntry 스텝 진행 해주세요🙂
끝까지 파이팅 입니다💪

2023-11-03 11:46 UTC, merged