step 2-4) EntityEntry 리뷰요청 드립니다!
next-step/jpa-entity-manager pull request #61
Opened 2023-11-01 11:47 UTC by limdingdong

정완님 안녕하세요!
4단계 EntityEntry 구현미션 수행하여 리뷰요청 드립니다!

제가 EntityEntry 개념을 잘 이해한건가 싶네요😂
엔티티 구현체와 영속상태의 묶음이라는 생각이 들어서
EntityEntry 를 엔티티 구현체와 엔티티 영속상태의 조합 클래스로 정의를 했습니다.

PersistenceContext 에서 영속화 처리 사이사이에 Entry 클래스의 상태를 변경하는 로직을 넣었습니다.
막상 이렇게 구현은 했는데... 딱히 상태정보를 확인해서 뭔가 처리하는 로직이 없으니 어색한 것 같다는 생각이 드네요😭
정완님 리뷰 받아서 방향을 잘 잡아보려고 합니다! 확인 한 번 해주시면 감사하겠습니다!

2023-11-01 12:50 UTC, ghojeong requested changes
임동섭 님!

마지막 Step 이고 어려웠을 텐데,
Hibernate 의 실제 구현과 거의 비슷하게끔 미션 의도를 잘 이해해주셨습니다. 👍 
EntityEntry 의 Status 가 어떻게 유의미하게 활용될 수 있을지 가볍게 의견을 남겨보았습니다.
다른 기능을 전부 구현하려면 너무 작업량이 많을 것 같고,
READ_ONLY 상태에 대하여 기능 구현을 하고 그에 관한 테스트 코드를 작성해주시면 감사하겠습니다.

2023-11-01 12:50 UTC, ghojeong commented on src/main/java/persistence/entity/EntityKey.java
> +    }
EntityKey 를 객체로 정의해주시며, equals 와 hashCode 를 선언해주신점 멋집니다! 👍 
나중에 EntityKey 의 기능을 확장하면 복합키의 대응도 가능하겠군요.

2023-11-01 12:50 UTC, ghojeong commented on src/main/java/persistence/entity/EntityStatus.java
> +    SAVING
[EntityStatus](https://github.com/hibernate/hibernate-orm/blob/8766c6f9732ae01ccde4680aeada4fef382cf826/hibernate-core/src/main/java/org/hibernate/engine/spi/Status.java#L15) 훌륭하게 잘 정의해주셨습니다!

2023-11-01 12:50 UTC, ghojeong commented on src/main/java/persistence/entity/EntityEntry.java
> +        this.entityStatus = entityStatus;
> 엔티티 구현체와 영속상태의 묶음이라는 생각이 들어서
> EntityEntry 를 엔티티 구현체와 엔티티 영속상태의 조합 클래스로 정의를 했습니다.

잘해주셨습니다!
본래 [EntityEntry](https://github.com/hibernate/hibernate-orm/blob/8766c6f9732ae01ccde4680aeada4fef382cf826/hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java#L99) 는 훨씬 많은 기능들이 있지만,
현재 Step 에서 할수 있는 정도로는 충분히 해주신것 같습니다.

2023-11-01 12:50 UTC, ghojeong commented on src/main/java/persistence/entity/EntityEntry.java
> +    }
실제 EntityEntry 에서도 EntityStatus 를 바꿀 때
성능을 위해 Status 객체를 int 값으로 압축하는 특이점이 있다는 것을 제외하고는 
똑같이 [setter 함수를 통해 Status 를 바꿉니다.](https://github.com/hibernate/hibernate-orm/blob/8766c6f9732ae01ccde4680aeada4fef382cf826/hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java#L181)

2023-11-01 12:50 UTC, ghojeong commented on src/main/java/persistence/entity/DefaultPersistenceContext.java
> +        entityEntry.manage();
> PersistenceContext 에서 영속화 처리 사이사이에 Entry 클래스의 상태를 변경하는 로직을 넣었습니다.

잘해주셨습니다. 실제 Hibernate 코드에서드 영속성 컨텍스트에서 addEntry 를 할 때
[Entry 클래스의 상태를 변경하는 로직을 실행합니다.](https://github.com/hibernate/hibernate-orm/blob/8766c6f9732ae01ccde4680aeada4fef382cf826/hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java#L688)

2023-11-01 12:50 UTC, ghojeong commented on src/main/java/persistence/entity/DefaultPersistenceContext.java
> +        entityEntry.delete();
> 막상 이렇게 구현은 했는데... 딱히 상태정보를 확인해서 뭔가 처리하는 로직이 없으니 어색한 것 같다는 생각이 드네요😭

이건 미션의 완성도 측면에서 저도 아쉬운 것 같습니다.
본래 없던 EntityEntry 가 2주차 미션에서 추가된 경위는 제가 낙관적 락 구현에 욕심을 냈기 때문입니다.

EntityStatus 가 제대로 활용되려면, SAVING 상태일 때는 다른 persist 함수가 동시에 일어지지 못하도록 락이 걸리거나,
같은 EntityKey 의 엔티티가 LOADING 중일 때는, select 쿼리가 중복해서 DB 에게 날려지지 않도록 기다려서 영속성 컨텍스트의 캐싱된 값을 가져오거나 하는 로직이 있어야 합니다.

하지만 멀티쓰레드 혹은 비동기 환경을 다루면서 미션을 진행하기에는 난이도와 작업량이 지나치게 상승해서,
그냥 이런게 있다 정도로 미션이 끝나버리는게 아쉬운 것 같습니다.

2023-11-01 12:50 UTC, ghojeong commented on src/main/java/persistence/entity/EntityStatus.java
> +    READ_ONLY,
> 막상 이렇게 구현은 했는데... 딱히 상태정보를 확인해서 뭔가 처리하는 로직이 없으니 어색한 것 같다는 생각이 드네요😭

다만 여러 EntityStatus 중에서도 READ_ONLY 는 이번 Step 에서도 도전을 해볼만한 부분인 것 같습니다.
PersistenceContext 에서 EntityStatus 를 확인하여,
만약 READ_ONLY Status 일 경우 update 및 delete 작업이 일어나지 않도록 막는 분기처리를 해주시기 바랍니다.

2023-11-02 03:49 UTC, limdingdong commented on src/main/java/persistence/entity/DefaultPersistenceContext.java
> +        entityEntry.delete();
오 JPA를 실무에서 사용해본 경험이 없어서 운영상황에서 발생할 수 있는
멀티쓰레드나 비동기 환경까지 고려할 생각은 못했었네요😅
그래도 정완님께서 미션의 취지를 설명해 주셔서 좋았습니다!
상태정보가 어떻게 쓰일 수 있는지 방향성을 안 것만으로도 의미가 크다고 생각해요!😆

2023-11-02 03:50 UTC, limdingdong commented on src/main/java/persistence/entity/EntityStatus.java
> +    READ_ONLY,
네 정완님 READ_ONLY 상태에 대한 처리로직 함 구현해서 요청드려보겠습니다! 피드백 감사합니다!

2023-11-02 04:02 UTC, limdingdong commented
정완님 안녕하세요!
피드백 내용 확인해서 Read Only 상태판별 로직을 추가해 보았습니다.

추가로 궁금한 점이 있어 코멘트를 남겼습니다.

addEntity 메서드에서 기존에 PersistenceContext 에 인스턴스가 영속화되어있지 않은 상태일 때는 (insert 처리 대상일 때)
EntityEntry 클래스도 존재하지 않기 때문에, 해당 Entity의 Read Only 상태를 알 수가 없습니다.

이럴 때에는 Entry 클래스가 아닌 Entity 클래스의 다른 메타정보 (찾아보니 @Immutable 애노테이션 같은게 있는데) 를 통해서
해당 엔티티의 읽기전용 대상여부를 판별해야 하는 것인지 궁금합니다!

2023-11-02 04:06 UTC, ghojeong commented
> 이럴 때에는 Entry 클래스가 아닌 Entity 클래스의 다른 메타정보를 통해서
> 해당 엔티티의 읽기전용 대상여부를 판별해야 하는 것인지 궁금합니다!

맞습니다. 다른 메타 정보를 통해서 READ_ONLY status 를 판별해야합니다.
이때 주로 쓰이는 것은 `@Transactional(readOnly = true)` 이지만,
저희 교육과정에서는 트랜잭션을 다루지 않으므로 여기까지 작업해주신 것만으로도 충분합니다.

2023-11-02 04:26 UTC, limdingdong commented
빠른 답변 감사드립니다 정완님!
트랜잭션 상태를 읽어야 할 수도 있는 것이었군요😆
어려운 내용이기는 한데, 또 다른 관점이 생긴 것 같네요ㅎㅎ

2023-11-02 04:54 UTC, ghojeong approved these changes
임동섭님!

함께 EntityManager 미션을 하며 참 즐거웠습니다! 👍 💯 
나머지 미션의 완주도 응원하겠습니다! 🔥

2023-11-02 04:55 UTC, merged